import re

translations = {
    "{0} role": "{0} jogosultság",
    "{0} user profile": "{0} adatlapja",
    "<0>{0}</0> configuration": "<0>{0}</0> konfigurációja",
    "<0>{0}</0>'s deletion is permanent and cannot be undone!": "<0>{0}</0> törlése végleges és nem vonható vissza!",
    "🔎 Checking access...": "🔎 Hozzáférés ellenőrzése...",
    "🔴 Not accessible at the provided address": "🔴 A megadott címen nem elérhető",
    "🟢 Access OK": "🟢 Hozzáférés rendben",
    "Account": "Fiókom",
    "Active {0}": "Aktív {0}",
    "Active playbacks and key details.": "Aktív lejátszások és főbb adatok.",
    "Actively seeding, the torrent will not be automatically deleted.": "Aktív seedben tartás, a torrent nem törlődik automatikusan.",
    "after {days} days": "{days} nap után",
    "After how many days?": "Hány nap után?",
    "All unused cache will be deleted!": "Minden nem használt cache törlésre kerül!",
    "An error occurred while loading StremHU Source!": "Hiba történt a StremHU Source betöltése közben!",
    "Are you sure you want to clear the cache?": "Biztosan törlöd a cache-t?",
    "Are you sure you want to delete {0}?": "Biztosan törlöd a(z) {0} trackert?",
    "Are you sure you want to delete it?": "Biztosan törlöd?",
    "Are you sure you want to delete?": "Biztosan törlöd?",
    "Are you sure you want to restart the application?": "Biztosan újraindítod az alkalmazást?",
    "Are you sure you want to run a manual check?": "Biztosan futtatod a kézi ellenőrzést?",
    "Automatic torrent deletion": "Automatikus torrent törlés",
    "Cache cleanup ran successfully.": "Cache törlés sikeresen lefutott.",
    "Cancel": "Mégsem",
    "Certificate expiration / renewal": "Tanúsítvány lejárat / megújítás",
    "Change password": "Jelszó módosítása",
    "Change username": "Felhasználónév módosítása",
    "Check torrents": "Torrentek ellenőrzése",
    "Checks completion based on the tracker, and can only be deleted after that.": "A tracker alapján ellenőrzi a teljesítést, és csak utána törölhető.",
    "Clear cache": "Cache törlés",
    "Configure excluded attributes": "Kizárt tulajdonságok konfigurációja",
    "Connection": "Kapcsolat",
    "Create": "Hozzáadás",
    "Create administrator account": "Adminisztrátori fiók létrehozása",
    "Current statistics of torrents and related operations.": "Torrentek aktuális statisztikái és a hozzájuk kapcsolódó műveletek.",
    "Dashboard": "Irányítópult",
    "days": "nap",
    "Delete": "Törlés",
    "Deleting \"{0}\" is permanent and cannot be undone!": "A \"{0}\" törlése végleges és nem vonható vissza!",
    "Deleting {0} will also delete all active torrents running on this tracker.": "A(z) {0} törlésével az összes aktív torrent is törlődik erről a trackerről.",
    "Deleting <0>{0}</0> will also delete its data.": "A(z) <0>{0}</0> törlésével az adatok is törlésre kerülnek.",
    "disable hiding": "elrejtés kikapcsolás",
    "Download": "Letöltés",
    "downloaded data | download speed | uploaded data | upload speed | total torrent size": "letöltött adat | letöltési sebesség | feltöltött adat | feltöltési sebesség | torrent teljes mérete",
    "Edit user profile": "Felhasználó adatlapjának szerkesztése",
    "Enter your username and password to log in": "Add meg a felhasználóneved és jelszavad a belépéshez",
    "Even if you run this, the scheduled check at dawn will still run.": "Ettől függetlenül a hajnali időzített ellenőrzés továbbra is lefut.",
    "Excludable attributes": "Kizárható tulajdonságok",
    "Excluded attributes": "Kizárt tulajdonságok",
    "Family friendly mode": "Családbarát mód",
    "Family-friendly mode": "Családbarát mód",
    "Files belonging to active torrents will not be deleted.": "Az aktív torrentekhez tartozó fájlok nem lesznek törölve.",
    "Found a bug?": "Hibát találtál?",
    "Full download": "Teljes letöltés",
    "Here you can fine-tune the appearance of torrent results (e.g. hide when there are few seeders), and turn on Family-friendly mode for a cleaner, simpler list.": "Itt finomhangolhatod a torrent-találatok megjelenését (pl. elrejtés kevés seeder esetén), és bekapcsolhatod a Családbarát módot a tisztább, egyszerűbb listához.",
    "History and details of started playbacks.": "Az elindított lejátszások előzményei és adatai.",
    "Hit'n'Run based deletion": "Hit'n'Run alapú törlés",
    "Home": "Kezdőlap",
    "if no seeders": "ha nincs seeder",
    "If the torrent contains an excluded attribute, it will not appear in the list.": "Amennyiben a torrent tartalmazza a kizárt tulajdonságot, az nem fog megjelenni a listában.",
    "If you experience any issues, you can restart the application.": "Ha bármilyen problémát tapasztalnál újraindíthatod az alkalmazást.",
    "If you like this project,": "Ha tetszik ez a projekt,",
    "In case of low seeders, playback might stutter. Under how many seeders should the torrent be hidden?": "Kevés seeder esetén, akadozhat a lejátszás, mennyi seeder alatt legyen rejtve a torrent?",
    "Keep seeding": "Seedben tartás",
    "Last IP sync": "Utolsó IP szinkronizáció",
    "Let's get started! Create the first account, which will have <0>Administrator</0> privileges.": "Kezdjünk is bele! Hozd létre az első fiókot, ami <0>Adminisztrátori</0> jogosultsággal fog rendelkezni.",
    "Limit concurrent streams": "Egyidejű lejátszások limitálása",
    "Limit the maximum number of concurrent streams. Leave empty for unlimited.": "Egyidejű lejátszások maximális száma. Ha üresen hagyod korlátlan lesz.",
    "Limit the number of connections.": "Kapcsolatok számának limitálása.",
    "Loading components": "Komponensek betöltése",
    "Log in": "Bejelentkezés",
    "Log in!": "Jelentkezz be!",
    "Log into your account": "Jelentkezz be a fiókodba",
    "Logged in as <0>{0}</0> user.": "Bejelentkezve mint <0>{0}</0> felhasználó.",
    "Logging out...": "Kijelentkezés folyamatban...",
    "Login": "Bejelentkezés",
    "Login and security": "Bejelentkezés és biztonság",
    "Logout": "Kijelentkezés",
    "Manage and configure your tracker logins.": "Tracker bejelentkezések kezelése és beállítása.",
    "Manage torrent files cache": "Torrent fájlok cache kezelése",
    "Manage users, roles, and access.": "Felhasználók, jogosultságok és hozzáférések kezelése.",
    "Manual check ran successfully.": "Kézi ellenőrzés sikeresen lefutott.",
    "Maximum connections per torrent": "Torrentenkénti kapcsolatok maximális száma",
    "Maximum download and upload speed. Leave empty for unlimited.": "Maximális letöltési és feltöltési sebesség. Ha üresen hagyod korlátlan lesz.",
    "Maximum global connections": "Globális kapcsolatok maximális száma",
    "Meaning of values shown under torrents": "Torrentek alatt látható értékek jelentése",
    "Must be a number": "Számnak kell lennie",
    "Must be a positive number.": "Pozitív számnak kell lennie.",
    "Need help?": "Segítségre van szükséged?",
    "Network access": "Hálózati hozzáférés",
    "Network access information": "Hálózati hozzáférés információk",
    "Network access is configured in environment variables.": "Hálózati hozzáférés környezeti változókból van konfigurálva.",
    "No active playbacks": "Nincs aktív lejátszás",
    "No active torrents": "Nincs aktív torrent",
    "No cache cleanup": "Nincs cache törlés",
    "No excluded attributes.": "Nincs kizárt tulajdonság.",
    "No limit": "Nincs limitálva",
    "No playback history": "Nincs lejátszási előzmény",
    "Only the best torrent appears based on your set preferences - so you don't have to choose from a list.": "Csak a legjobb torrent jelenik meg a beállított preferenciáid alapján - így nem kell listából válogatni.",
    "Only the best torrent is displayed based on your preferences - so you don't have to pick from a list.": "Csak a legjobb torrent jelenik meg a beállított preferenciáid alapján - így nem kell listából válogatni.",
    "Open details": "Adatlap megnyitása",
    "Other preferences": "További preferenciák",
    "Partial download": "Részleges letöltés",
    "Password": "Jelszó",
    "Password is required": "Jelszó kötelező",
    "Playback based deletion": "Lejátszás alapú törlés",
    "Playback history": "Lejátszási előzmények",
    "Playback time: {0}": "Lejátszás ideje: {0}",
    "Port for incoming connections": "Port a bejövő kapcsolatokhoz",
    "Preferences": "Preferenciák",
    "Read the documentation": "Olvasd el a dokumentációt",
    "Reload": "Újratöltés",
    "Report on Discord": "Jelentsd be Discordon",
    "Reset download to tracker setting": "Letöltés visszaállítása a torrent oldal beállításra",
    "Restart": "Újraindítás",
    "Restart initiated! Reload the page in a few seconds!": "Újraindítás elindítva! Pár másodperc múlva frissítsd az oldalt!",
    "Role": "Jogosultság",
    "Settings": "Beállítások",
    "Source: {0}": "Forrás: {0}",
    "Specify how long after unused torrent files should be deleted": "Add meg, mennyi idő után kerüljenek törlésre a nem használt torrent fájlok",
    "Speed": "Sebesség",
    "Start checking torrents!": "Torrentek ellenőrzésének elindítása!",
    "Stop seeding": "Seedben tartás megszüntetése",
    "support it on Ko-Fi": "támogasd Ko-Fi-n",
    "The check runs every day at dawn, but a torrent is only deleted if all the set conditions are met.": "Az ellenőrzés minden nap hajnalban lefut, viszont a torrent csak akkor kerül törlésre, ha minden beállított feltétel teljesül.",
    "The torrent can only be deleted if the set time has passed since the last playback.": "A torrent csak abban az esetben törölhető, ha eltelt a megadott idő az utolsó lejátszás óta.",
    "These attributes can be excluded, meaning torrents with these attributes won't appear in the clients' list.": "Ezek a tulajdonságok kizárhatók, amiknek az a hatása, hogy a kliensek listázójában nem fognak megjelenni a kizárt tulajdonsággal rendelkező torrentek.",
    "To use StremHU Source, you must log in to at least one tracker!": "A StremHU Source használatához kötelező legalább 1 trackerhez bejelentkezned!",
    "Torrent added at: {0}": "Torrent hozzáadás időpontja: {0}",
    "Torrent availability": "Torrent elérhetősége",
    "Torrents containing an excluded attribute will not appear in the list in clients.": "A kliensekben megjelenő listában nem fognak szerepelni azok a torrent-ek, amik tartalmaznák a kizárt tulajdonságot.",
    "Torrents for the started media will appear here.": "Az elindított médiákhoz tartozó torrentek itt fognak megjelenni.",
    "Trackers": "Trackerek",
    "under 10 seeders": "10 seeder alatt",
    "under 5 seeders": "5 seeder alatt",
    "Update": "Módosítás",
    "Update network access or apply new configuration.": "Hálózati hozzáférés frissítése, új konfiguráció alkalmazása.",
    "Upload": "Feltöltés",
    "Use UPnP / NAT-PMP on the router for port forwarding": "UPnP / NAT-PMP használata a routeren a porttovábbításhoz",
    "Used port": "Használt port",
    "User: {0}": "Felhasználó: {0}",
    "Username": "Felhasználónév",
    "Username is required": "Felhasználónév kötelező",
    "With few seeders, playback might stutter. Below how many seeders should the torrent be hidden?": "Kevés seeder esetén, akadozhat a lejátszás, mennyi seeder alatt legyen rejtve a torrent?",
    "You can change your username or password": "Módosíthatod felhasználóneved vagy jelszavadat",
    "You will need to log in again after changing your password": "A jelszó módósítása után újra be kell jelentkezned",
    "You will need to log in again after changing your username": "A felhasználónév módósítása után újra be kell jelentkezned",
    "Supported clients": "Támogatott kliensek",
    "Connect StremHU Source to the clients you use.": "Csatlakoztasd a StremHU Source-ot az általad használt kliensekhez.",
    "During the StremHU addon login process, the following URL must be entered.": "StremHU addon bejelentkezés folyamatánál a következő URL-t kell megadni.",
    "Copy URL": "URL másolása",
    "Paste the copied URL into your addons.": "A kimásolt URL-t illeszd be az addonok közé.",
    "Install in app": "Telepítés appban",
    "Opens the application and adds the addon.": "Megnyitja az alkalmazást és hozzáadja az addont.",
    "Install on web": "Telepítés weben",
    "You can install the addon with confirmation on the website.": "A weboldalon jóváhagyással telepítheted az addont.",
    "You can change your account data, security settings, and torrent list preferences.": "Módosíthatod a fiókadataidat, biztonsági beállításaidat és a torrentlista preferenciáit.",
    "{0} - Login and security": "{0} - Bejelentkezés és biztonság",
    "Manage login details, password and security settings.": "Bejelentkezési adatok, jelszó és biztonsági beállítások kezelése.",
    "{0} - Torrent list customization": "{0} - Torrent lista személyreszabása",
    "Configure what appears first in the results and what to exclude.": "Állítsd be, mi kerüljön előre a találatok között, és mit zárjunk ki.",
    "System configuration and user management.": "Rendszer konfigurálása és felhasználók kezelése.",
    "Manage torrent sites, configure StremHU Source.": "Torrent oldalak kezelése, StremHU Source konfigurálása.",
    "Create user accounts, manage and update profile data.": "Felhasználói fiókok létrehozása, profiladatok kezelése és frissítése.",
    "View current and past playbacks.": "Aktuális és múltbeli lejátszások megtekintése.",
    "You can customize which torrents appear first in the list. The preferred attributes affect the order.": "Testreszabhatod, milyen torrentek kerüljenek előre a listában. A preferált tulajdonságok befolyásolják a sorrendet.",
    "No rules with preferred attributes.": "Nincs preferált tulajdonsággal rendelkező szabály.",
    "Are you sure you want to request a new key?": "Biztosan kérsz új kulcsot?",
    "After generating a new key, the addon will not work in the installed applications until you reinstall it!": "Új kulcs létrehozása után az telepített alkalmazásokban az addon nem fog működni amíg újra nem telepíted!",
    "New key generation is complete.": "Új kulcs generálása elkészült.",
    "Manage key": "Kulcs kezelése",
    "StremHU Source uses this key to identify the user in the applications.": "A StremHU Source ennek a kulcsnak a segítségével azonosítja a felhasználót az alkalmazásokban.",
    "Request a new key": "Új kulcs kérése",
    "Available attributes": "Elérhető tulajdonságok",
    "You can prefer or exclude these attributes.": "Ezeket a tulajdonságokat tudod preferálni vagy kizárni.",
    "No more available attributes.": "Nincs több elérhető tulajdonság.",
    "Preferred attributes": "Preferált tulajdonságok",
    "The attributes you add here will appear higher in the list.": "Azok a tulajdonságok, amiket ide hozzáadsz előrébb kerülnek a listában.",
    "No preferred attributes": "Nincs preferált tulajdonság",
    "Create preference configuration": "Preferencia konfiguráció létrehozása",
    "Choose which preference configuration you want to create and configure it.": "Válaszd ki milyen preferencia konfigurációt szeretnél létrehozni és végezd el a konfigurációt."
}

with open('/Users/benedekbalint/Development/stremhu-source/client/src/locales/hu/messages.po', 'r') as f:
    content = f.read()

import re

def replacer(match):
    msgid = match.group(1)
    # unescape msgid to match dictionary
    msgid_unescaped = msgid.replace('\\"', '"').replace('\\n', '\n')
    if msgid_unescaped in translations:
        # escape msgstr
        msgstr = translations[msgid_unescaped].replace('"', '\\"').replace('\n', '\\n')
        return f'msgid "{msgid}"\nmsgstr "{msgstr}"'
    else:
        print(f"Warning: Missing translation for: {msgid_unescaped}")
        return match.group(0)

# The pattern looks for msgid "..." followed by msgstr "..."
new_content = re.sub(r'msgid "(.*?)"\nmsgstr ".*?"', replacer, content)

with open('/Users/benedekbalint/Development/stremhu-source/client/src/locales/hu/messages.po', 'w') as f:
    f.write(new_content)

print("PO file updated.")
