/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ProtectedRelayRouteRouteImport } from './routes/_protected/relay/route'
import { Route as ProtectedDashboardRouteRouteImport } from './routes/_protected/dashboard/route'
import { Route as SetupUserIndexRouteImport } from './routes/setup/user/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedRelayIndexRouteImport } from './routes/_protected/relay/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedSettingsPreferencesRouteRouteImport } from './routes/_protected/settings/preferences/route'
import { Route as ProtectedSettingsAccountRouteRouteImport } from './routes/_protected/settings/account/route'
import { Route as ProtectedRelayTorrentsRouteRouteImport } from './routes/_protected/relay/torrents/route'
import { Route as ProtectedRelaySettingsRouteRouteImport } from './routes/_protected/relay/settings/route'
import { Route as ProtectedDashboardUsersRouteRouteImport } from './routes/_protected/dashboard/users/route'
import { Route as ProtectedDashboardSystemRouteRouteImport } from './routes/_protected/dashboard/system/route'
import { Route as ProtectedSetupAddressIndexRouteImport } from './routes/_protected/setup/address/index'
import { Route as ProtectedSettingsPreferencesIndexRouteImport } from './routes/_protected/settings/preferences/index'
import { Route as ProtectedSettingsAccountIndexRouteImport } from './routes/_protected/settings/account/index'
import { Route as ProtectedRelayTorrentsIndexRouteImport } from './routes/_protected/relay/torrents/index'
import { Route as ProtectedRelaySettingsIndexRouteImport } from './routes/_protected/relay/settings/index'
import { Route as ProtectedDashboardUsersIndexRouteImport } from './routes/_protected/dashboard/users/index'
import { Route as ProtectedDashboardSystemIndexRouteImport } from './routes/_protected/dashboard/system/index'
import { Route as ProtectedSettingsPreferencesCreateRouteRouteImport } from './routes/_protected/settings/preferences/create/route'
import { Route as ProtectedSettingsPreferencesPreferenceRouteRouteImport } from './routes/_protected/settings/preferences/$preference/route'
import { Route as ProtectedDashboardUsersUserIdRouteRouteImport } from './routes/_protected/dashboard/users/$userId/route'
import { Route as ProtectedSettingsPreferencesCreateIndexRouteImport } from './routes/_protected/settings/preferences/create/index'
import { Route as ProtectedSettingsPreferencesPreferenceIndexRouteImport } from './routes/_protected/settings/preferences/$preference/index'
import { Route as ProtectedDashboardUsersUserIdIndexRouteImport } from './routes/_protected/dashboard/users/$userId/index'
import { Route as ProtectedDashboardUsersUserIdPreferencesRouteRouteImport } from './routes/_protected/dashboard/users/$userId/preferences/route'
import { Route as ProtectedDashboardUsersUserIdPreferencesIndexRouteImport } from './routes/_protected/dashboard/users/$userId/preferences/index'
import { Route as ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteImport } from './routes/_protected/dashboard/users/$userId/preferences/$preference/route'
import { Route as ProtectedDashboardUsersUserIdPreferencesCreateIndexRouteImport } from './routes/_protected/dashboard/users/$userId/preferences/create/index'
import { Route as ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRouteImport } from './routes/_protected/dashboard/users/$userId/preferences/$preference/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRelayRouteRoute = ProtectedRelayRouteRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRouteRoute = ProtectedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const SetupUserIndexRoute = SetupUserIndexRouteImport.update({
  id: '/setup/user/',
  path: '/setup/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedRelayIndexRoute = ProtectedRelayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRelayRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRouteRoute,
} as any)
const ProtectedSettingsPreferencesRouteRoute =
  ProtectedSettingsPreferencesRouteRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsAccountRouteRoute =
  ProtectedSettingsAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedRelayTorrentsRouteRoute =
  ProtectedRelayTorrentsRouteRouteImport.update({
    id: '/torrents',
    path: '/torrents',
    getParentRoute: () => ProtectedRelayRouteRoute,
  } as any)
const ProtectedRelaySettingsRouteRoute =
  ProtectedRelaySettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedRelayRouteRoute,
  } as any)
const ProtectedDashboardUsersRouteRoute =
  ProtectedDashboardUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedDashboardSystemRouteRoute =
  ProtectedDashboardSystemRouteRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)
const ProtectedSetupAddressIndexRoute =
  ProtectedSetupAddressIndexRouteImport.update({
    id: '/setup/address/',
    path: '/setup/address/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPreferencesIndexRoute =
  ProtectedSettingsPreferencesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsPreferencesRouteRoute,
  } as any)
const ProtectedSettingsAccountIndexRoute =
  ProtectedSettingsAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsAccountRouteRoute,
  } as any)
const ProtectedRelayTorrentsIndexRoute =
  ProtectedRelayTorrentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedRelayTorrentsRouteRoute,
  } as any)
const ProtectedRelaySettingsIndexRoute =
  ProtectedRelaySettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedRelaySettingsRouteRoute,
  } as any)
const ProtectedDashboardUsersIndexRoute =
  ProtectedDashboardUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardUsersRouteRoute,
  } as any)
const ProtectedDashboardSystemIndexRoute =
  ProtectedDashboardSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardSystemRouteRoute,
  } as any)
const ProtectedSettingsPreferencesCreateRouteRoute =
  ProtectedSettingsPreferencesCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ProtectedSettingsPreferencesRouteRoute,
  } as any)
const ProtectedSettingsPreferencesPreferenceRouteRoute =
  ProtectedSettingsPreferencesPreferenceRouteRouteImport.update({
    id: '/$preference',
    path: '/$preference',
    getParentRoute: () => ProtectedSettingsPreferencesRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdRouteRoute =
  ProtectedDashboardUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ProtectedDashboardUsersRouteRoute,
  } as any)
const ProtectedSettingsPreferencesCreateIndexRoute =
  ProtectedSettingsPreferencesCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsPreferencesCreateRouteRoute,
  } as any)
const ProtectedSettingsPreferencesPreferenceIndexRoute =
  ProtectedSettingsPreferencesPreferenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsPreferencesPreferenceRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdIndexRoute =
  ProtectedDashboardUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardUsersUserIdRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdPreferencesRouteRoute =
  ProtectedDashboardUsersUserIdPreferencesRouteRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ProtectedDashboardUsersUserIdRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdPreferencesIndexRoute =
  ProtectedDashboardUsersUserIdPreferencesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardUsersUserIdPreferencesRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute =
  ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteImport.update({
    id: '/$preference',
    path: '/$preference',
    getParentRoute: () => ProtectedDashboardUsersUserIdPreferencesRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute =
  ProtectedDashboardUsersUserIdPreferencesCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => ProtectedDashboardUsersUserIdPreferencesRouteRoute,
  } as any)
const ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute =
  ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/relay': typeof ProtectedRelayRouteRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/dashboard/system': typeof ProtectedDashboardSystemRouteRouteWithChildren
  '/dashboard/users': typeof ProtectedDashboardUsersRouteRouteWithChildren
  '/relay/settings': typeof ProtectedRelaySettingsRouteRouteWithChildren
  '/relay/torrents': typeof ProtectedRelayTorrentsRouteRouteWithChildren
  '/settings/account': typeof ProtectedSettingsAccountRouteRouteWithChildren
  '/settings/preferences': typeof ProtectedSettingsPreferencesRouteRouteWithChildren
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/relay/': typeof ProtectedRelayIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/setup/user/': typeof SetupUserIndexRoute
  '/dashboard/users/$userId': typeof ProtectedDashboardUsersUserIdRouteRouteWithChildren
  '/settings/preferences/$preference': typeof ProtectedSettingsPreferencesPreferenceRouteRouteWithChildren
  '/settings/preferences/create': typeof ProtectedSettingsPreferencesCreateRouteRouteWithChildren
  '/dashboard/system/': typeof ProtectedDashboardSystemIndexRoute
  '/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/relay/settings/': typeof ProtectedRelaySettingsIndexRoute
  '/relay/torrents/': typeof ProtectedRelayTorrentsIndexRoute
  '/settings/account/': typeof ProtectedSettingsAccountIndexRoute
  '/settings/preferences/': typeof ProtectedSettingsPreferencesIndexRoute
  '/setup/address/': typeof ProtectedSetupAddressIndexRoute
  '/dashboard/users/$userId/preferences': typeof ProtectedDashboardUsersUserIdPreferencesRouteRouteWithChildren
  '/dashboard/users/$userId/': typeof ProtectedDashboardUsersUserIdIndexRoute
  '/settings/preferences/$preference/': typeof ProtectedSettingsPreferencesPreferenceIndexRoute
  '/settings/preferences/create/': typeof ProtectedSettingsPreferencesCreateIndexRoute
  '/dashboard/users/$userId/preferences/$preference': typeof ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteWithChildren
  '/dashboard/users/$userId/preferences/': typeof ProtectedDashboardUsersUserIdPreferencesIndexRoute
  '/dashboard/users/$userId/preferences/$preference/': typeof ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute
  '/dashboard/users/$userId/preferences/create/': typeof ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/setup': typeof SetupIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/relay': typeof ProtectedRelayIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/setup/user': typeof SetupUserIndexRoute
  '/dashboard/system': typeof ProtectedDashboardSystemIndexRoute
  '/dashboard/users': typeof ProtectedDashboardUsersIndexRoute
  '/relay/settings': typeof ProtectedRelaySettingsIndexRoute
  '/relay/torrents': typeof ProtectedRelayTorrentsIndexRoute
  '/settings/account': typeof ProtectedSettingsAccountIndexRoute
  '/settings/preferences': typeof ProtectedSettingsPreferencesIndexRoute
  '/setup/address': typeof ProtectedSetupAddressIndexRoute
  '/dashboard/users/$userId': typeof ProtectedDashboardUsersUserIdIndexRoute
  '/settings/preferences/$preference': typeof ProtectedSettingsPreferencesPreferenceIndexRoute
  '/settings/preferences/create': typeof ProtectedSettingsPreferencesCreateIndexRoute
  '/dashboard/users/$userId/preferences': typeof ProtectedDashboardUsersUserIdPreferencesIndexRoute
  '/dashboard/users/$userId/preferences/$preference': typeof ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute
  '/dashboard/users/$userId/preferences/create': typeof ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/_protected/relay': typeof ProtectedRelayRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_protected/dashboard/system': typeof ProtectedDashboardSystemRouteRouteWithChildren
  '/_protected/dashboard/users': typeof ProtectedDashboardUsersRouteRouteWithChildren
  '/_protected/relay/settings': typeof ProtectedRelaySettingsRouteRouteWithChildren
  '/_protected/relay/torrents': typeof ProtectedRelayTorrentsRouteRouteWithChildren
  '/_protected/settings/account': typeof ProtectedSettingsAccountRouteRouteWithChildren
  '/_protected/settings/preferences': typeof ProtectedSettingsPreferencesRouteRouteWithChildren
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/relay/': typeof ProtectedRelayIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/setup/user/': typeof SetupUserIndexRoute
  '/_protected/dashboard/users/$userId': typeof ProtectedDashboardUsersUserIdRouteRouteWithChildren
  '/_protected/settings/preferences/$preference': typeof ProtectedSettingsPreferencesPreferenceRouteRouteWithChildren
  '/_protected/settings/preferences/create': typeof ProtectedSettingsPreferencesCreateRouteRouteWithChildren
  '/_protected/dashboard/system/': typeof ProtectedDashboardSystemIndexRoute
  '/_protected/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/_protected/relay/settings/': typeof ProtectedRelaySettingsIndexRoute
  '/_protected/relay/torrents/': typeof ProtectedRelayTorrentsIndexRoute
  '/_protected/settings/account/': typeof ProtectedSettingsAccountIndexRoute
  '/_protected/settings/preferences/': typeof ProtectedSettingsPreferencesIndexRoute
  '/_protected/setup/address/': typeof ProtectedSetupAddressIndexRoute
  '/_protected/dashboard/users/$userId/preferences': typeof ProtectedDashboardUsersUserIdPreferencesRouteRouteWithChildren
  '/_protected/dashboard/users/$userId/': typeof ProtectedDashboardUsersUserIdIndexRoute
  '/_protected/settings/preferences/$preference/': typeof ProtectedSettingsPreferencesPreferenceIndexRoute
  '/_protected/settings/preferences/create/': typeof ProtectedSettingsPreferencesCreateIndexRoute
  '/_protected/dashboard/users/$userId/preferences/$preference': typeof ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteWithChildren
  '/_protected/dashboard/users/$userId/preferences/': typeof ProtectedDashboardUsersUserIdPreferencesIndexRoute
  '/_protected/dashboard/users/$userId/preferences/$preference/': typeof ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute
  '/_protected/dashboard/users/$userId/preferences/create/': typeof ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/dashboard'
    | '/relay'
    | '/settings'
    | '/login/'
    | '/setup/'
    | '/dashboard/system'
    | '/dashboard/users'
    | '/relay/settings'
    | '/relay/torrents'
    | '/settings/account'
    | '/settings/preferences'
    | '/dashboard/'
    | '/relay/'
    | '/settings/'
    | '/setup/user/'
    | '/dashboard/users/$userId'
    | '/settings/preferences/$preference'
    | '/settings/preferences/create'
    | '/dashboard/system/'
    | '/dashboard/users/'
    | '/relay/settings/'
    | '/relay/torrents/'
    | '/settings/account/'
    | '/settings/preferences/'
    | '/setup/address/'
    | '/dashboard/users/$userId/preferences'
    | '/dashboard/users/$userId/'
    | '/settings/preferences/$preference/'
    | '/settings/preferences/create/'
    | '/dashboard/users/$userId/preferences/$preference'
    | '/dashboard/users/$userId/preferences/'
    | '/dashboard/users/$userId/preferences/$preference/'
    | '/dashboard/users/$userId/preferences/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/'
    | '/login'
    | '/setup'
    | '/dashboard'
    | '/relay'
    | '/settings'
    | '/setup/user'
    | '/dashboard/system'
    | '/dashboard/users'
    | '/relay/settings'
    | '/relay/torrents'
    | '/settings/account'
    | '/settings/preferences'
    | '/setup/address'
    | '/dashboard/users/$userId'
    | '/settings/preferences/$preference'
    | '/settings/preferences/create'
    | '/dashboard/users/$userId/preferences'
    | '/dashboard/users/$userId/preferences/$preference'
    | '/dashboard/users/$userId/preferences/create'
  id:
    | '__root__'
    | '/_protected'
    | '/logout'
    | '/_protected/dashboard'
    | '/_protected/relay'
    | '/_protected/settings'
    | '/_protected/'
    | '/login/'
    | '/setup/'
    | '/_protected/dashboard/system'
    | '/_protected/dashboard/users'
    | '/_protected/relay/settings'
    | '/_protected/relay/torrents'
    | '/_protected/settings/account'
    | '/_protected/settings/preferences'
    | '/_protected/dashboard/'
    | '/_protected/relay/'
    | '/_protected/settings/'
    | '/setup/user/'
    | '/_protected/dashboard/users/$userId'
    | '/_protected/settings/preferences/$preference'
    | '/_protected/settings/preferences/create'
    | '/_protected/dashboard/system/'
    | '/_protected/dashboard/users/'
    | '/_protected/relay/settings/'
    | '/_protected/relay/torrents/'
    | '/_protected/settings/account/'
    | '/_protected/settings/preferences/'
    | '/_protected/setup/address/'
    | '/_protected/dashboard/users/$userId/preferences'
    | '/_protected/dashboard/users/$userId/'
    | '/_protected/settings/preferences/$preference/'
    | '/_protected/settings/preferences/create/'
    | '/_protected/dashboard/users/$userId/preferences/$preference'
    | '/_protected/dashboard/users/$userId/preferences/'
    | '/_protected/dashboard/users/$userId/preferences/$preference/'
    | '/_protected/dashboard/users/$userId/preferences/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  SetupUserIndexRoute: typeof SetupUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/relay': {
      id: '/_protected/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof ProtectedRelayRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/setup/user/': {
      id: '/setup/user/'
      path: '/setup/user'
      fullPath: '/setup/user/'
      preLoaderRoute: typeof SetupUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/relay/': {
      id: '/_protected/relay/'
      path: '/'
      fullPath: '/relay/'
      preLoaderRoute: typeof ProtectedRelayIndexRouteImport
      parentRoute: typeof ProtectedRelayRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/settings/preferences': {
      id: '/_protected/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ProtectedSettingsPreferencesRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/relay/torrents': {
      id: '/_protected/relay/torrents'
      path: '/torrents'
      fullPath: '/relay/torrents'
      preLoaderRoute: typeof ProtectedRelayTorrentsRouteRouteImport
      parentRoute: typeof ProtectedRelayRouteRoute
    }
    '/_protected/relay/settings': {
      id: '/_protected/relay/settings'
      path: '/settings'
      fullPath: '/relay/settings'
      preLoaderRoute: typeof ProtectedRelaySettingsRouteRouteImport
      parentRoute: typeof ProtectedRelayRouteRoute
    }
    '/_protected/dashboard/users': {
      id: '/_protected/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof ProtectedDashboardUsersRouteRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/dashboard/system': {
      id: '/_protected/dashboard/system'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof ProtectedDashboardSystemRouteRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/setup/address/': {
      id: '/_protected/setup/address/'
      path: '/setup/address'
      fullPath: '/setup/address/'
      preLoaderRoute: typeof ProtectedSetupAddressIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/preferences/': {
      id: '/_protected/settings/preferences/'
      path: '/'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof ProtectedSettingsPreferencesIndexRouteImport
      parentRoute: typeof ProtectedSettingsPreferencesRouteRoute
    }
    '/_protected/settings/account/': {
      id: '/_protected/settings/account/'
      path: '/'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof ProtectedSettingsAccountIndexRouteImport
      parentRoute: typeof ProtectedSettingsAccountRouteRoute
    }
    '/_protected/relay/torrents/': {
      id: '/_protected/relay/torrents/'
      path: '/'
      fullPath: '/relay/torrents/'
      preLoaderRoute: typeof ProtectedRelayTorrentsIndexRouteImport
      parentRoute: typeof ProtectedRelayTorrentsRouteRoute
    }
    '/_protected/relay/settings/': {
      id: '/_protected/relay/settings/'
      path: '/'
      fullPath: '/relay/settings/'
      preLoaderRoute: typeof ProtectedRelaySettingsIndexRouteImport
      parentRoute: typeof ProtectedRelaySettingsRouteRoute
    }
    '/_protected/dashboard/users/': {
      id: '/_protected/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof ProtectedDashboardUsersIndexRouteImport
      parentRoute: typeof ProtectedDashboardUsersRouteRoute
    }
    '/_protected/dashboard/system/': {
      id: '/_protected/dashboard/system/'
      path: '/'
      fullPath: '/dashboard/system/'
      preLoaderRoute: typeof ProtectedDashboardSystemIndexRouteImport
      parentRoute: typeof ProtectedDashboardSystemRouteRoute
    }
    '/_protected/settings/preferences/create': {
      id: '/_protected/settings/preferences/create'
      path: '/create'
      fullPath: '/settings/preferences/create'
      preLoaderRoute: typeof ProtectedSettingsPreferencesCreateRouteRouteImport
      parentRoute: typeof ProtectedSettingsPreferencesRouteRoute
    }
    '/_protected/settings/preferences/$preference': {
      id: '/_protected/settings/preferences/$preference'
      path: '/$preference'
      fullPath: '/settings/preferences/$preference'
      preLoaderRoute: typeof ProtectedSettingsPreferencesPreferenceRouteRouteImport
      parentRoute: typeof ProtectedSettingsPreferencesRouteRoute
    }
    '/_protected/dashboard/users/$userId': {
      id: '/_protected/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdRouteRouteImport
      parentRoute: typeof ProtectedDashboardUsersRouteRoute
    }
    '/_protected/settings/preferences/create/': {
      id: '/_protected/settings/preferences/create/'
      path: '/'
      fullPath: '/settings/preferences/create/'
      preLoaderRoute: typeof ProtectedSettingsPreferencesCreateIndexRouteImport
      parentRoute: typeof ProtectedSettingsPreferencesCreateRouteRoute
    }
    '/_protected/settings/preferences/$preference/': {
      id: '/_protected/settings/preferences/$preference/'
      path: '/'
      fullPath: '/settings/preferences/$preference/'
      preLoaderRoute: typeof ProtectedSettingsPreferencesPreferenceIndexRouteImport
      parentRoute: typeof ProtectedSettingsPreferencesPreferenceRouteRoute
    }
    '/_protected/dashboard/users/$userId/': {
      id: '/_protected/dashboard/users/$userId/'
      path: '/'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdIndexRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdRouteRoute
    }
    '/_protected/dashboard/users/$userId/preferences': {
      id: '/_protected/dashboard/users/$userId/preferences'
      path: '/preferences'
      fullPath: '/dashboard/users/$userId/preferences'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdPreferencesRouteRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdRouteRoute
    }
    '/_protected/dashboard/users/$userId/preferences/': {
      id: '/_protected/dashboard/users/$userId/preferences/'
      path: '/'
      fullPath: '/dashboard/users/$userId/preferences/'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdPreferencesIndexRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdPreferencesRouteRoute
    }
    '/_protected/dashboard/users/$userId/preferences/$preference': {
      id: '/_protected/dashboard/users/$userId/preferences/$preference'
      path: '/$preference'
      fullPath: '/dashboard/users/$userId/preferences/$preference'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdPreferencesRouteRoute
    }
    '/_protected/dashboard/users/$userId/preferences/create/': {
      id: '/_protected/dashboard/users/$userId/preferences/create/'
      path: '/create'
      fullPath: '/dashboard/users/$userId/preferences/create/'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdPreferencesCreateIndexRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdPreferencesRouteRoute
    }
    '/_protected/dashboard/users/$userId/preferences/$preference/': {
      id: '/_protected/dashboard/users/$userId/preferences/$preference/'
      path: '/'
      fullPath: '/dashboard/users/$userId/preferences/$preference/'
      preLoaderRoute: typeof ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRouteImport
      parentRoute: typeof ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute
    }
  }
}

interface ProtectedDashboardSystemRouteRouteChildren {
  ProtectedDashboardSystemIndexRoute: typeof ProtectedDashboardSystemIndexRoute
}

const ProtectedDashboardSystemRouteRouteChildren: ProtectedDashboardSystemRouteRouteChildren =
  {
    ProtectedDashboardSystemIndexRoute: ProtectedDashboardSystemIndexRoute,
  }

const ProtectedDashboardSystemRouteRouteWithChildren =
  ProtectedDashboardSystemRouteRoute._addFileChildren(
    ProtectedDashboardSystemRouteRouteChildren,
  )

interface ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteChildren {
  ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute: typeof ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute
}

const ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteChildren: ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteChildren =
  {
    ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute:
      ProtectedDashboardUsersUserIdPreferencesPreferenceIndexRoute,
  }

const ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteWithChildren =
  ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute._addFileChildren(
    ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteChildren,
  )

interface ProtectedDashboardUsersUserIdPreferencesRouteRouteChildren {
  ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute: typeof ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteWithChildren
  ProtectedDashboardUsersUserIdPreferencesIndexRoute: typeof ProtectedDashboardUsersUserIdPreferencesIndexRoute
  ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute: typeof ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute
}

const ProtectedDashboardUsersUserIdPreferencesRouteRouteChildren: ProtectedDashboardUsersUserIdPreferencesRouteRouteChildren =
  {
    ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRoute:
      ProtectedDashboardUsersUserIdPreferencesPreferenceRouteRouteWithChildren,
    ProtectedDashboardUsersUserIdPreferencesIndexRoute:
      ProtectedDashboardUsersUserIdPreferencesIndexRoute,
    ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute:
      ProtectedDashboardUsersUserIdPreferencesCreateIndexRoute,
  }

const ProtectedDashboardUsersUserIdPreferencesRouteRouteWithChildren =
  ProtectedDashboardUsersUserIdPreferencesRouteRoute._addFileChildren(
    ProtectedDashboardUsersUserIdPreferencesRouteRouteChildren,
  )

interface ProtectedDashboardUsersUserIdRouteRouteChildren {
  ProtectedDashboardUsersUserIdPreferencesRouteRoute: typeof ProtectedDashboardUsersUserIdPreferencesRouteRouteWithChildren
  ProtectedDashboardUsersUserIdIndexRoute: typeof ProtectedDashboardUsersUserIdIndexRoute
}

const ProtectedDashboardUsersUserIdRouteRouteChildren: ProtectedDashboardUsersUserIdRouteRouteChildren =
  {
    ProtectedDashboardUsersUserIdPreferencesRouteRoute:
      ProtectedDashboardUsersUserIdPreferencesRouteRouteWithChildren,
    ProtectedDashboardUsersUserIdIndexRoute:
      ProtectedDashboardUsersUserIdIndexRoute,
  }

const ProtectedDashboardUsersUserIdRouteRouteWithChildren =
  ProtectedDashboardUsersUserIdRouteRoute._addFileChildren(
    ProtectedDashboardUsersUserIdRouteRouteChildren,
  )

interface ProtectedDashboardUsersRouteRouteChildren {
  ProtectedDashboardUsersUserIdRouteRoute: typeof ProtectedDashboardUsersUserIdRouteRouteWithChildren
  ProtectedDashboardUsersIndexRoute: typeof ProtectedDashboardUsersIndexRoute
}

const ProtectedDashboardUsersRouteRouteChildren: ProtectedDashboardUsersRouteRouteChildren =
  {
    ProtectedDashboardUsersUserIdRouteRoute:
      ProtectedDashboardUsersUserIdRouteRouteWithChildren,
    ProtectedDashboardUsersIndexRoute: ProtectedDashboardUsersIndexRoute,
  }

const ProtectedDashboardUsersRouteRouteWithChildren =
  ProtectedDashboardUsersRouteRoute._addFileChildren(
    ProtectedDashboardUsersRouteRouteChildren,
  )

interface ProtectedDashboardRouteRouteChildren {
  ProtectedDashboardSystemRouteRoute: typeof ProtectedDashboardSystemRouteRouteWithChildren
  ProtectedDashboardUsersRouteRoute: typeof ProtectedDashboardUsersRouteRouteWithChildren
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteRouteChildren: ProtectedDashboardRouteRouteChildren =
  {
    ProtectedDashboardSystemRouteRoute:
      ProtectedDashboardSystemRouteRouteWithChildren,
    ProtectedDashboardUsersRouteRoute:
      ProtectedDashboardUsersRouteRouteWithChildren,
    ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  }

const ProtectedDashboardRouteRouteWithChildren =
  ProtectedDashboardRouteRoute._addFileChildren(
    ProtectedDashboardRouteRouteChildren,
  )

interface ProtectedRelaySettingsRouteRouteChildren {
  ProtectedRelaySettingsIndexRoute: typeof ProtectedRelaySettingsIndexRoute
}

const ProtectedRelaySettingsRouteRouteChildren: ProtectedRelaySettingsRouteRouteChildren =
  {
    ProtectedRelaySettingsIndexRoute: ProtectedRelaySettingsIndexRoute,
  }

const ProtectedRelaySettingsRouteRouteWithChildren =
  ProtectedRelaySettingsRouteRoute._addFileChildren(
    ProtectedRelaySettingsRouteRouteChildren,
  )

interface ProtectedRelayTorrentsRouteRouteChildren {
  ProtectedRelayTorrentsIndexRoute: typeof ProtectedRelayTorrentsIndexRoute
}

const ProtectedRelayTorrentsRouteRouteChildren: ProtectedRelayTorrentsRouteRouteChildren =
  {
    ProtectedRelayTorrentsIndexRoute: ProtectedRelayTorrentsIndexRoute,
  }

const ProtectedRelayTorrentsRouteRouteWithChildren =
  ProtectedRelayTorrentsRouteRoute._addFileChildren(
    ProtectedRelayTorrentsRouteRouteChildren,
  )

interface ProtectedRelayRouteRouteChildren {
  ProtectedRelaySettingsRouteRoute: typeof ProtectedRelaySettingsRouteRouteWithChildren
  ProtectedRelayTorrentsRouteRoute: typeof ProtectedRelayTorrentsRouteRouteWithChildren
  ProtectedRelayIndexRoute: typeof ProtectedRelayIndexRoute
}

const ProtectedRelayRouteRouteChildren: ProtectedRelayRouteRouteChildren = {
  ProtectedRelaySettingsRouteRoute:
    ProtectedRelaySettingsRouteRouteWithChildren,
  ProtectedRelayTorrentsRouteRoute:
    ProtectedRelayTorrentsRouteRouteWithChildren,
  ProtectedRelayIndexRoute: ProtectedRelayIndexRoute,
}

const ProtectedRelayRouteRouteWithChildren =
  ProtectedRelayRouteRoute._addFileChildren(ProtectedRelayRouteRouteChildren)

interface ProtectedSettingsAccountRouteRouteChildren {
  ProtectedSettingsAccountIndexRoute: typeof ProtectedSettingsAccountIndexRoute
}

const ProtectedSettingsAccountRouteRouteChildren: ProtectedSettingsAccountRouteRouteChildren =
  {
    ProtectedSettingsAccountIndexRoute: ProtectedSettingsAccountIndexRoute,
  }

const ProtectedSettingsAccountRouteRouteWithChildren =
  ProtectedSettingsAccountRouteRoute._addFileChildren(
    ProtectedSettingsAccountRouteRouteChildren,
  )

interface ProtectedSettingsPreferencesPreferenceRouteRouteChildren {
  ProtectedSettingsPreferencesPreferenceIndexRoute: typeof ProtectedSettingsPreferencesPreferenceIndexRoute
}

const ProtectedSettingsPreferencesPreferenceRouteRouteChildren: ProtectedSettingsPreferencesPreferenceRouteRouteChildren =
  {
    ProtectedSettingsPreferencesPreferenceIndexRoute:
      ProtectedSettingsPreferencesPreferenceIndexRoute,
  }

const ProtectedSettingsPreferencesPreferenceRouteRouteWithChildren =
  ProtectedSettingsPreferencesPreferenceRouteRoute._addFileChildren(
    ProtectedSettingsPreferencesPreferenceRouteRouteChildren,
  )

interface ProtectedSettingsPreferencesCreateRouteRouteChildren {
  ProtectedSettingsPreferencesCreateIndexRoute: typeof ProtectedSettingsPreferencesCreateIndexRoute
}

const ProtectedSettingsPreferencesCreateRouteRouteChildren: ProtectedSettingsPreferencesCreateRouteRouteChildren =
  {
    ProtectedSettingsPreferencesCreateIndexRoute:
      ProtectedSettingsPreferencesCreateIndexRoute,
  }

const ProtectedSettingsPreferencesCreateRouteRouteWithChildren =
  ProtectedSettingsPreferencesCreateRouteRoute._addFileChildren(
    ProtectedSettingsPreferencesCreateRouteRouteChildren,
  )

interface ProtectedSettingsPreferencesRouteRouteChildren {
  ProtectedSettingsPreferencesPreferenceRouteRoute: typeof ProtectedSettingsPreferencesPreferenceRouteRouteWithChildren
  ProtectedSettingsPreferencesCreateRouteRoute: typeof ProtectedSettingsPreferencesCreateRouteRouteWithChildren
  ProtectedSettingsPreferencesIndexRoute: typeof ProtectedSettingsPreferencesIndexRoute
}

const ProtectedSettingsPreferencesRouteRouteChildren: ProtectedSettingsPreferencesRouteRouteChildren =
  {
    ProtectedSettingsPreferencesPreferenceRouteRoute:
      ProtectedSettingsPreferencesPreferenceRouteRouteWithChildren,
    ProtectedSettingsPreferencesCreateRouteRoute:
      ProtectedSettingsPreferencesCreateRouteRouteWithChildren,
    ProtectedSettingsPreferencesIndexRoute:
      ProtectedSettingsPreferencesIndexRoute,
  }

const ProtectedSettingsPreferencesRouteRouteWithChildren =
  ProtectedSettingsPreferencesRouteRoute._addFileChildren(
    ProtectedSettingsPreferencesRouteRouteChildren,
  )

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsAccountRouteRoute: typeof ProtectedSettingsAccountRouteRouteWithChildren
  ProtectedSettingsPreferencesRouteRoute: typeof ProtectedSettingsPreferencesRouteRouteWithChildren
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsAccountRouteRoute:
      ProtectedSettingsAccountRouteRouteWithChildren,
    ProtectedSettingsPreferencesRouteRoute:
      ProtectedSettingsPreferencesRouteRouteWithChildren,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedDashboardRouteRoute: typeof ProtectedDashboardRouteRouteWithChildren
  ProtectedRelayRouteRoute: typeof ProtectedRelayRouteRouteWithChildren
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSetupAddressIndexRoute: typeof ProtectedSetupAddressIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRouteRoute: ProtectedDashboardRouteRouteWithChildren,
  ProtectedRelayRouteRoute: ProtectedRelayRouteRouteWithChildren,
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSetupAddressIndexRoute: ProtectedSetupAddressIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  LoginIndexRoute: LoginIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  SetupUserIndexRoute: SetupUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
