/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as SetupUserIndexRouteImport } from './routes/setup/user/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSettingsUsersRouteRouteImport } from './routes/_protected/settings/users/route'
import { Route as ProtectedSettingsTorrentClientRouteRouteImport } from './routes/_protected/settings/torrent-client/route'
import { Route as ProtectedSettingsSystemRouteRouteImport } from './routes/_protected/settings/system/route'
import { Route as ProtectedSetupAddressIndexRouteImport } from './routes/_protected/setup/address/index'
import { Route as ProtectedSettingsUsersIndexRouteImport } from './routes/_protected/settings/users/index'
import { Route as ProtectedSettingsTorrentClientIndexRouteImport } from './routes/_protected/settings/torrent-client/index'
import { Route as ProtectedSettingsSystemIndexRouteImport } from './routes/_protected/settings/system/index'
import { Route as ProtectedSettingsUsersUserIdRouteRouteImport } from './routes/_protected/settings/users/$userId/route'
import { Route as ProtectedSettingsUsersUserIdIndexRouteImport } from './routes/_protected/settings/users/$userId/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const SetupUserIndexRoute = SetupUserIndexRouteImport.update({
  id: '/setup/user/',
  path: '/setup/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsUsersRouteRoute =
  ProtectedSettingsUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsTorrentClientRouteRoute =
  ProtectedSettingsTorrentClientRouteRouteImport.update({
    id: '/torrent-client',
    path: '/torrent-client',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsSystemRouteRoute =
  ProtectedSettingsSystemRouteRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSetupAddressIndexRoute =
  ProtectedSetupAddressIndexRouteImport.update({
    id: '/setup/address/',
    path: '/setup/address/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsUsersIndexRoute =
  ProtectedSettingsUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsUsersRouteRoute,
  } as any)
const ProtectedSettingsTorrentClientIndexRoute =
  ProtectedSettingsTorrentClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsTorrentClientRouteRoute,
  } as any)
const ProtectedSettingsSystemIndexRoute =
  ProtectedSettingsSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsSystemRouteRoute,
  } as any)
const ProtectedSettingsUsersUserIdRouteRoute =
  ProtectedSettingsUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ProtectedSettingsUsersRouteRoute,
  } as any)
const ProtectedSettingsUsersUserIdIndexRoute =
  ProtectedSettingsUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/setup': typeof SetupIndexRoute
  '/settings/system': typeof ProtectedSettingsSystemRouteRouteWithChildren
  '/settings/torrent-client': typeof ProtectedSettingsTorrentClientRouteRouteWithChildren
  '/settings/users': typeof ProtectedSettingsUsersRouteRouteWithChildren
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/setup/user': typeof SetupUserIndexRoute
  '/settings/users/$userId': typeof ProtectedSettingsUsersUserIdRouteRouteWithChildren
  '/settings/system/': typeof ProtectedSettingsSystemIndexRoute
  '/settings/torrent-client/': typeof ProtectedSettingsTorrentClientIndexRoute
  '/settings/users/': typeof ProtectedSettingsUsersIndexRoute
  '/setup/address': typeof ProtectedSetupAddressIndexRoute
  '/settings/users/$userId/': typeof ProtectedSettingsUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/setup': typeof SetupIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/setup/user': typeof SetupUserIndexRoute
  '/settings/system': typeof ProtectedSettingsSystemIndexRoute
  '/settings/torrent-client': typeof ProtectedSettingsTorrentClientIndexRoute
  '/settings/users': typeof ProtectedSettingsUsersIndexRoute
  '/setup/address': typeof ProtectedSetupAddressIndexRoute
  '/settings/users/$userId': typeof ProtectedSettingsUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_protected/settings/system': typeof ProtectedSettingsSystemRouteRouteWithChildren
  '/_protected/settings/torrent-client': typeof ProtectedSettingsTorrentClientRouteRouteWithChildren
  '/_protected/settings/users': typeof ProtectedSettingsUsersRouteRouteWithChildren
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/setup/user/': typeof SetupUserIndexRoute
  '/_protected/settings/users/$userId': typeof ProtectedSettingsUsersUserIdRouteRouteWithChildren
  '/_protected/settings/system/': typeof ProtectedSettingsSystemIndexRoute
  '/_protected/settings/torrent-client/': typeof ProtectedSettingsTorrentClientIndexRoute
  '/_protected/settings/users/': typeof ProtectedSettingsUsersIndexRoute
  '/_protected/setup/address/': typeof ProtectedSetupAddressIndexRoute
  '/_protected/settings/users/$userId/': typeof ProtectedSettingsUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/settings'
    | '/'
    | '/login'
    | '/setup'
    | '/settings/system'
    | '/settings/torrent-client'
    | '/settings/users'
    | '/settings/'
    | '/setup/user'
    | '/settings/users/$userId'
    | '/settings/system/'
    | '/settings/torrent-client/'
    | '/settings/users/'
    | '/setup/address'
    | '/settings/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/'
    | '/login'
    | '/setup'
    | '/settings'
    | '/setup/user'
    | '/settings/system'
    | '/settings/torrent-client'
    | '/settings/users'
    | '/setup/address'
    | '/settings/users/$userId'
  id:
    | '__root__'
    | '/_protected'
    | '/logout'
    | '/_protected/settings'
    | '/_protected/'
    | '/login/'
    | '/setup/'
    | '/_protected/settings/system'
    | '/_protected/settings/torrent-client'
    | '/_protected/settings/users'
    | '/_protected/settings/'
    | '/setup/user/'
    | '/_protected/settings/users/$userId'
    | '/_protected/settings/system/'
    | '/_protected/settings/torrent-client/'
    | '/_protected/settings/users/'
    | '/_protected/setup/address/'
    | '/_protected/settings/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  SetupUserIndexRoute: typeof SetupUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/setup/user/': {
      id: '/setup/user/'
      path: '/setup/user'
      fullPath: '/setup/user'
      preLoaderRoute: typeof SetupUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/users': {
      id: '/_protected/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof ProtectedSettingsUsersRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/torrent-client': {
      id: '/_protected/settings/torrent-client'
      path: '/torrent-client'
      fullPath: '/settings/torrent-client'
      preLoaderRoute: typeof ProtectedSettingsTorrentClientRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/system': {
      id: '/_protected/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof ProtectedSettingsSystemRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/setup/address/': {
      id: '/_protected/setup/address/'
      path: '/setup/address'
      fullPath: '/setup/address'
      preLoaderRoute: typeof ProtectedSetupAddressIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users/': {
      id: '/_protected/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof ProtectedSettingsUsersIndexRouteImport
      parentRoute: typeof ProtectedSettingsUsersRouteRoute
    }
    '/_protected/settings/torrent-client/': {
      id: '/_protected/settings/torrent-client/'
      path: '/'
      fullPath: '/settings/torrent-client/'
      preLoaderRoute: typeof ProtectedSettingsTorrentClientIndexRouteImport
      parentRoute: typeof ProtectedSettingsTorrentClientRouteRoute
    }
    '/_protected/settings/system/': {
      id: '/_protected/settings/system/'
      path: '/'
      fullPath: '/settings/system/'
      preLoaderRoute: typeof ProtectedSettingsSystemIndexRouteImport
      parentRoute: typeof ProtectedSettingsSystemRouteRoute
    }
    '/_protected/settings/users/$userId': {
      id: '/_protected/settings/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof ProtectedSettingsUsersUserIdRouteRouteImport
      parentRoute: typeof ProtectedSettingsUsersRouteRoute
    }
    '/_protected/settings/users/$userId/': {
      id: '/_protected/settings/users/$userId/'
      path: '/'
      fullPath: '/settings/users/$userId/'
      preLoaderRoute: typeof ProtectedSettingsUsersUserIdIndexRouteImport
      parentRoute: typeof ProtectedSettingsUsersUserIdRouteRoute
    }
  }
}

interface ProtectedSettingsSystemRouteRouteChildren {
  ProtectedSettingsSystemIndexRoute: typeof ProtectedSettingsSystemIndexRoute
}

const ProtectedSettingsSystemRouteRouteChildren: ProtectedSettingsSystemRouteRouteChildren =
  {
    ProtectedSettingsSystemIndexRoute: ProtectedSettingsSystemIndexRoute,
  }

const ProtectedSettingsSystemRouteRouteWithChildren =
  ProtectedSettingsSystemRouteRoute._addFileChildren(
    ProtectedSettingsSystemRouteRouteChildren,
  )

interface ProtectedSettingsTorrentClientRouteRouteChildren {
  ProtectedSettingsTorrentClientIndexRoute: typeof ProtectedSettingsTorrentClientIndexRoute
}

const ProtectedSettingsTorrentClientRouteRouteChildren: ProtectedSettingsTorrentClientRouteRouteChildren =
  {
    ProtectedSettingsTorrentClientIndexRoute:
      ProtectedSettingsTorrentClientIndexRoute,
  }

const ProtectedSettingsTorrentClientRouteRouteWithChildren =
  ProtectedSettingsTorrentClientRouteRoute._addFileChildren(
    ProtectedSettingsTorrentClientRouteRouteChildren,
  )

interface ProtectedSettingsUsersUserIdRouteRouteChildren {
  ProtectedSettingsUsersUserIdIndexRoute: typeof ProtectedSettingsUsersUserIdIndexRoute
}

const ProtectedSettingsUsersUserIdRouteRouteChildren: ProtectedSettingsUsersUserIdRouteRouteChildren =
  {
    ProtectedSettingsUsersUserIdIndexRoute:
      ProtectedSettingsUsersUserIdIndexRoute,
  }

const ProtectedSettingsUsersUserIdRouteRouteWithChildren =
  ProtectedSettingsUsersUserIdRouteRoute._addFileChildren(
    ProtectedSettingsUsersUserIdRouteRouteChildren,
  )

interface ProtectedSettingsUsersRouteRouteChildren {
  ProtectedSettingsUsersUserIdRouteRoute: typeof ProtectedSettingsUsersUserIdRouteRouteWithChildren
  ProtectedSettingsUsersIndexRoute: typeof ProtectedSettingsUsersIndexRoute
}

const ProtectedSettingsUsersRouteRouteChildren: ProtectedSettingsUsersRouteRouteChildren =
  {
    ProtectedSettingsUsersUserIdRouteRoute:
      ProtectedSettingsUsersUserIdRouteRouteWithChildren,
    ProtectedSettingsUsersIndexRoute: ProtectedSettingsUsersIndexRoute,
  }

const ProtectedSettingsUsersRouteRouteWithChildren =
  ProtectedSettingsUsersRouteRoute._addFileChildren(
    ProtectedSettingsUsersRouteRouteChildren,
  )

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsSystemRouteRoute: typeof ProtectedSettingsSystemRouteRouteWithChildren
  ProtectedSettingsTorrentClientRouteRoute: typeof ProtectedSettingsTorrentClientRouteRouteWithChildren
  ProtectedSettingsUsersRouteRoute: typeof ProtectedSettingsUsersRouteRouteWithChildren
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsSystemRouteRoute:
      ProtectedSettingsSystemRouteRouteWithChildren,
    ProtectedSettingsTorrentClientRouteRoute:
      ProtectedSettingsTorrentClientRouteRouteWithChildren,
    ProtectedSettingsUsersRouteRoute:
      ProtectedSettingsUsersRouteRouteWithChildren,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSetupAddressIndexRoute: typeof ProtectedSetupAddressIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSetupAddressIndexRoute: ProtectedSetupAddressIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  LoginIndexRoute: LoginIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  SetupUserIndexRoute: SetupUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
