/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * StremHU Relay
 * OpenAPI spec version: 0.1.0
 */
import { relayClientInstance } from './relay-client-instance';

export interface AddTorrent {
  torrentFilePath: string;
  downloadFullTorrent?: boolean | null;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Health {
  ok?: boolean;
  startTime: number;
}

export interface RelayTorrent {
  /** checking_files=1, downloading_metadata=2, downloading=3, finished=4, seeding=5, unused_enum_for_backwards_compatibility_allocating=6, checking_resume_data=7 https://www.libtorrent.org/reference-Torrent_Status.html#torrent_status */
  state: number;
  progress: number;
  name: string;
  infoHash: string;
  downloadSpeed: number;
  uploadSpeed: number;
  downloaded: number;
  uploaded: number;
  total: number;
  maxConnections: number;
  connections: number;
}

export interface RelayTorrentState {
  /** checking_files=1, downloading_metadata=2, downloading=3, finished=4, seeding=5, unused_enum_for_backwards_compatibility_allocating=6, checking_resume_data=7 https://www.libtorrent.org/reference-Torrent_Status.html#torrent_status */
  state: number;
  progress: number;
}

export interface UpdateRelayTorrent {
  downloadFullTorrent?: boolean | null;
}

export interface UpdateSettings {
  downloadLimit?: number | null;
  uploadLimit?: number | null;
  port?: number | null;
  connectionsLimit?: number | null;
  torrentConnectionsLimit?: number | null;
  enableUpnpAndNatpmp?: boolean | null;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health
 */
export const health = (
  options?: SecondParameter<typeof relayClientInstance<Health>>,
) => {
  return relayClientInstance<Health>(
    { url: `/health`, method: 'GET' },
    options,
  );
};

/**
 * @summary Update
 */
export const update = (
  updateSettings: UpdateSettings,
  options?: SecondParameter<typeof relayClientInstance<unknown>>,
) => {
  return relayClientInstance<unknown>(
    {
      url: `/setting/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateSettings,
    },
    options,
  );
};

/**
 * @summary Get Torrents
 */
export const getTorrents = (
  options?: SecondParameter<typeof relayClientInstance<RelayTorrent[]>>,
) => {
  return relayClientInstance<RelayTorrent[]>(
    { url: `/torrents/`, method: 'GET' },
    options,
  );
};

/**
 * @summary Add Torrent
 */
export const addTorrent = (
  addTorrent: AddTorrent,
  options?: SecondParameter<typeof relayClientInstance<RelayTorrent>>,
) => {
  return relayClientInstance<RelayTorrent>(
    {
      url: `/torrents/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addTorrent,
    },
    options,
  );
};

/**
 * @summary Get Torrent
 */
export const getTorrent = (
  infoHash: string,
  options?: SecondParameter<typeof relayClientInstance<RelayTorrent>>,
) => {
  return relayClientInstance<RelayTorrent>(
    { url: `/torrents/${infoHash}`, method: 'GET' },
    options,
  );
};

/**
 * @summary Update Torrent
 */
export const updateTorrent = (
  infoHash: string,
  updateRelayTorrent: UpdateRelayTorrent,
  options?: SecondParameter<typeof relayClientInstance<RelayTorrent>>,
) => {
  return relayClientInstance<RelayTorrent>(
    {
      url: `/torrents/${infoHash}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateRelayTorrent,
    },
    options,
  );
};

/**
 * @summary Delete Torrent
 */
export const deleteTorrent = (
  infoHash: string,
  options?: SecondParameter<typeof relayClientInstance<RelayTorrent>>,
) => {
  return relayClientInstance<RelayTorrent>(
    { url: `/torrents/${infoHash}`, method: 'DELETE' },
    options,
  );
};

/**
 * @summary Get Torrent State
 */
export const getTorrentState = (
  infoHash: string,
  options?: SecondParameter<typeof relayClientInstance<RelayTorrentState>>,
) => {
  return relayClientInstance<RelayTorrentState>(
    { url: `/torrents/${infoHash}/verification`, method: 'GET' },
    options,
  );
};

/**
 * @summary Stream
 */
export const headStreamFile = (
  infoHash: string,
  fileIndex: number,
  options?: SecondParameter<typeof relayClientInstance<unknown>>,
) => {
  return relayClientInstance<unknown>(
    { url: `/stream/${infoHash}/${fileIndex}`, method: 'HEAD' },
    options,
  );
};

/**
 * @summary Stream
 */
export const getStreamFile = (
  infoHash: string,
  fileIndex: number,
  options?: SecondParameter<typeof relayClientInstance<unknown>>,
) => {
  return relayClientInstance<unknown>(
    { url: `/stream/${infoHash}/${fileIndex}`, method: 'GET' },
    options,
  );
};

export type HealthResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type UpdateResult = NonNullable<Awaited<ReturnType<typeof update>>>;
export type GetTorrentsResult = NonNullable<
  Awaited<ReturnType<typeof getTorrents>>
>;
export type AddTorrentResult = NonNullable<
  Awaited<ReturnType<typeof addTorrent>>
>;
export type GetTorrentResult = NonNullable<
  Awaited<ReturnType<typeof getTorrent>>
>;
export type UpdateTorrentResult = NonNullable<
  Awaited<ReturnType<typeof updateTorrent>>
>;
export type DeleteTorrentResult = NonNullable<
  Awaited<ReturnType<typeof deleteTorrent>>
>;
export type GetTorrentStateResult = NonNullable<
  Awaited<ReturnType<typeof getTorrentState>>
>;
export type HeadStreamFileResult = NonNullable<
  Awaited<ReturnType<typeof headStreamFile>>
>;
export type GetStreamFileResult = NonNullable<
  Awaited<ReturnType<typeof getStreamFile>>
>;
