/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { SourceClient } from './SourceClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AudioPreferenceDto } from './models/AudioPreferenceDto';
export { AudioQualityEnum } from './models/AudioQualityEnum';
export type { AudioQualityMetaDto } from './models/AudioQualityMetaDto';
export type { AudioQualityPreferenceMetaDto } from './models/AudioQualityPreferenceMetaDto';
export type { AuthLoginDto } from './models/AuthLoginDto';
export type { BehaviorHintsDto } from './models/BehaviorHintsDto';
export type { CatalogHealthDto } from './models/CatalogHealthDto';
export type { CreateSetupDto } from './models/CreateSetupDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { HealthDto } from './models/HealthDto';
export { LanguageEnum } from './models/LanguageEnum';
export type { LanguageMetaDto } from './models/LanguageMetaDto';
export type { LanguagePreferenceDto } from './models/LanguagePreferenceDto';
export type { LanguagePreferenceMetaDto } from './models/LanguagePreferenceMetaDto';
export type { LocalUrlDto } from './models/LocalUrlDto';
export type { LocalUrlRequestDto } from './models/LocalUrlRequestDto';
export type { LoginTrackerDto } from './models/LoginTrackerDto';
export type { ManifestDto } from './models/ManifestDto';
export type { MeDto } from './models/MeDto';
export type { MetadataDto } from './models/MetadataDto';
export { PreferenceEnum } from './models/PreferenceEnum';
export type { RelaySettingsDto } from './models/RelaySettingsDto';
export { ResolutionEnum } from './models/ResolutionEnum';
export type { ResolutionMetaDto } from './models/ResolutionMetaDto';
export type { ResolutionPreferenceDto } from './models/ResolutionPreferenceDto';
export type { ResolutionPreferenceMetaDto } from './models/ResolutionPreferenceMetaDto';
export type { SettingDto } from './models/SettingDto';
export { SourceEnum } from './models/SourceEnum';
export type { SourceMetaDto } from './models/SourceMetaDto';
export type { SourcePreferenceDto } from './models/SourcePreferenceDto';
export type { SourcePreferenceMetaDto } from './models/SourcePreferenceMetaDto';
export type { StatusDto } from './models/StatusDto';
export type { StreamDto } from './models/StreamDto';
export type { StreamsResponseDto } from './models/StreamsResponseDto';
export type { TorrentDto } from './models/TorrentDto';
export type { TrackerDto } from './models/TrackerDto';
export { TrackerEnum } from './models/TrackerEnum';
export type { TrackerMetaDto } from './models/TrackerMetaDto';
export type { TrackerPreferenceDto } from './models/TrackerPreferenceDto';
export type { TrackerPreferenceMetaDto } from './models/TrackerPreferenceMetaDto';
export type { UpdateExternalSettingDto } from './models/UpdateExternalSettingDto';
export type { UpdateMeDto } from './models/UpdateMeDto';
export type { UpdateRelaySettingsDto } from './models/UpdateRelaySettingsDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateTorrentDto } from './models/UpdateTorrentDto';
export type { UpdateTrackerDto } from './models/UpdateTrackerDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UserDto } from './models/UserDto';
export { UserRoleEnum } from './models/UserRoleEnum';
export type { UserRoleMetaDto } from './models/UserRoleMetaDto';
export type { VideoPreferenceDto } from './models/VideoPreferenceDto';
export { VideoQualityEnum } from './models/VideoQualityEnum';
export type { VideoQualityMetaDto } from './models/VideoQualityMetaDto';
export type { VideoQualityPreferenceMetaDto } from './models/VideoQualityPreferenceMetaDto';

export { AppService } from './services/AppService';
export { AuthenticationService } from './services/AuthenticationService';
export { ExternalRelaySettingsService } from './services/ExternalRelaySettingsService';
export { MeService } from './services/MeService';
export { MetadataService } from './services/MetadataService';
export { SettingsService } from './services/SettingsService';
export { StremHuCatalogService } from './services/StremHuCatalogService';
export { StremioManifestService } from './services/StremioManifestService';
export { StremioPlaybackService } from './services/StremioPlaybackService';
export { StremioStreamsService } from './services/StremioStreamsService';
export { TorrentsService } from './services/TorrentsService';
export { TorrentsCacheService } from './services/TorrentsCacheService';
export { TrackersService } from './services/TrackersService';
export { UsersService } from './services/UsersService';
