"""rename_best_torrent_to_smart_filter

Revision ID: 00e4b6a295c8
Revises: f0ae5cdeaf91
Create Date: 2026-07-09 22:38:03.893271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00e4b6a295c8"
down_revision: str | None = "f0ae5cdeaf91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_best_torrent_grouping",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "only_best_torrent",
            new_column_name="enable_smart_filter",
            existing_type=sa.Boolean(),
        )
        batch_op.add_column(
            sa.Column("smart_filter_grouping_preference_id", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "smart_filter_limit",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_users_smart_filter_grouping_preference_id_preferences"),
            "preferences",
            ["smart_filter_grouping_preference_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "enable_smart_filter",
            new_column_name="only_best_torrent",
            existing_type=sa.Boolean(),
        )
        batch_op.drop_constraint(
            batch_op.f("fk_users_smart_filter_grouping_preference_id_preferences"),
            type_="foreignkey",
        )
        batch_op.drop_column("smart_filter_limit")
        batch_op.drop_column("smart_filter_grouping_preference_id")

    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.drop_column("allow_best_torrent_grouping")

    # ### end Alembic commands ###
