"""Add strict_exclusion to PreferenceModel

Revision ID: c30e6d9dd16d
Revises: 3a7b9c1d2e3f
Create Date: 2026-09-04 19:33:24.817639

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c30e6d9dd16d"
down_revision: str | None = "3a7b9c1d2e3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "strict_exclusion",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.drop_column("strict_exclusion")

    # ### end Alembic commands ###
