"""Initial database

Revision ID: f0ae5cdeaf91
Revises:
Create Date: 2026-06-15 20:01:01.780515

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0ae5cdeaf91"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("multiple", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferences")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "attributes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("preference_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["preferences.id"],
            name=op.f("fk_attributes_preference_id_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributes")),
    )
    op.create_table(
        "preference_definitions",
        sa.Column("preference_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["preferences.id"],
            name=op.f("fk_preference_definitions_preference_id_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preference_definitions")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("torrent_seed", sa.Integer(), nullable=True),
        sa.Column("only_best_torrent", sa.Boolean(), nullable=False),
        sa.Column("max_concurrent_streams", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_api_key"), ["api_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "attribute_exclusions",
        sa.Column("attribute_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_attribute_exclusions_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_attribute_exclusions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_exclusions")),
    )
    with op.batch_alter_table("attribute_exclusions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attribute_exclusions_attribute_id"),
            ["attribute_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_attribute_exclusions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "uq_attribute_exclusions_system",
            ["attribute_id"],
            unique=True,
            sqlite_where=sa.text("user_id IS NULL"),
        )
        batch_op.create_index(
            "uq_attribute_exclusions_user",
            ["attribute_id", "user_id"],
            unique=True,
            sqlite_where=sa.text("user_id IS NOT NULL"),
        )

    op.create_table(
        "indexer_definitions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("details_path", sa.String(), nullable=False),
        sa.Column("requires_full_download", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["attributes.id"],
            name=op.f("fk_indexer_definitions_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indexer_definitions")),
    )
    op.create_table(
        "media_attributes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=True),
        sa.Column("is_preferable", sa.Boolean(), nullable=False),
        sa.Column("show_in_details", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["attributes.id"],
            name=op.f("fk_media_attributes_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_attributes")),
    )
    op.create_table(
        "pairings",
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_code", sa.String(), nullable=False),
        sa.Column("device_code", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pairings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pairings")),
    )
    with op.batch_alter_table("pairings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pairings_device_code"), ["device_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pairings_user_code"), ["user_code"], unique=False
        )

    op.create_table(
        "preference_definition_attributes",
        sa.Column("definition_id", sa.String(), nullable=False),
        sa.Column("attribute_id", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_preference_definition_attributes_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["preference_definitions.id"],
            name=op.f(
                "fk_preference_definition_attributes_definition_id_preference_definitions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preference_definition_attributes")),
    )
    op.create_table(
        "system_preference_definitions",
        sa.Column("definition_id", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["preference_definitions.id"],
            name=op.f(
                "fk_system_preference_definitions_definition_id_preference_definitions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "definition_id", name=op.f("pk_system_preference_definitions")
        ),
    )
    op.create_table(
        "user_preference_definitions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("definition_id", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["preference_definitions.id"],
            name=op.f(
                "fk_user_preference_definitions_definition_id_preference_definitions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preference_definitions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preference_definitions")),
    )
    op.create_table(
        "indexer_accounts",
        sa.Column("indexer_id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("hit_and_run", sa.Boolean(), nullable=True),
        sa.Column("keep_seed_seconds", sa.Integer(), nullable=True),
        sa.Column("download_full_torrent", sa.Boolean(), nullable=False),
        sa.Column("cookies", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer_definitions.id"],
            name=op.f("fk_indexer_accounts_indexer_id_indexer_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("indexer_id", name=op.f("pk_indexer_accounts")),
    )
    op.create_table(
        "playback_histories",
        sa.Column("playback_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("indexer_id", sa.String(), nullable=False),
        sa.Column("torrent_id", sa.String(), nullable=False),
        sa.Column("file_index", sa.Integer(), nullable=False),
        sa.Column("torrent_name", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("imdb_info", sa.JSON(), nullable=True),
        sa.Column("client", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer_definitions.id"],
            name=op.f("fk_playback_histories_indexer_id_indexer_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_playback_histories_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("playback_id", name=op.f("pk_playback_histories")),
    )
    with op.batch_alter_table("playback_histories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playback_histories_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playback_histories_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_playback_history_indexer_torrent",
            ["indexer_id", "torrent_id"],
            unique=False,
        )

    op.create_table(
        "torrent_files",
        sa.Column("indexer_id", sa.String(), nullable=False),
        sa.Column("torrent_id", sa.String(), nullable=False),
        sa.Column("info_hash", sa.String(), nullable=False),
        sa.Column("torrent_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer_accounts.indexer_id"],
            name=op.f("fk_torrent_files_indexer_id_indexer_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "indexer_id", "torrent_id", name=op.f("pk_torrent_files")
        ),
    )
    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_torrent_files_info_hash"), ["info_hash"], unique=False
        )

    op.create_table(
        "torrents",
        sa.Column("info_hash", sa.String(), nullable=False),
        sa.Column("indexer_id", sa.String(), nullable=False),
        sa.Column("torrent_id", sa.String(), nullable=False),
        sa.Column("is_persisted", sa.Boolean(), nullable=False),
        sa.Column("full_download", sa.Boolean(), nullable=True),
        sa.Column("resume_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indexer_id", "torrent_id"],
            ["torrent_files.indexer_id", "torrent_files.torrent_id"],
            name="fk_torrents_torrent_files",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer_accounts.indexer_id"],
            name=op.f("fk_torrents_indexer_id_indexer_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("info_hash", "indexer_id", name=op.f("pk_torrents")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("torrents")
    with op.batch_alter_table("torrent_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_torrent_files_info_hash"))

    op.drop_table("torrent_files")
    with op.batch_alter_table("playback_histories", schema=None) as batch_op:
        batch_op.drop_index("ix_playback_history_indexer_torrent")
        batch_op.drop_index(batch_op.f("ix_playback_histories_user_id"))
        batch_op.drop_index(batch_op.f("ix_playback_histories_created_at"))

    op.drop_table("playback_histories")
    op.drop_table("indexer_accounts")
    op.drop_table("user_preference_definitions")
    op.drop_table("system_preference_definitions")
    op.drop_table("preference_definition_attributes")
    with op.batch_alter_table("pairings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pairings_user_code"))
        batch_op.drop_index(batch_op.f("ix_pairings_device_code"))

    op.drop_table("pairings")
    op.drop_table("media_attributes")
    op.drop_table("indexer_definitions")
    with op.batch_alter_table("attribute_exclusions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_attribute_exclusions_user", sqlite_where=sa.text("user_id IS NOT NULL")
        )
        batch_op.drop_index(
            "uq_attribute_exclusions_system", sqlite_where=sa.text("user_id IS NULL")
        )
        batch_op.drop_index(batch_op.f("ix_attribute_exclusions_user_id"))
        batch_op.drop_index(batch_op.f("ix_attribute_exclusions_attribute_id"))

    op.drop_table("attribute_exclusions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_api_key"))

    op.drop_table("users")
    op.drop_table("preference_definitions")
    op.drop_table("attributes")
    op.drop_table("settings")
    op.drop_table("roles")
    op.drop_table("preferences")
    # ### end Alembic commands ###
