/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * StremHU Catalog - Public
 * OpenAPI spec version: 1.0.0
 */
import { catalogClientInstance } from './catalog-client-instance';

export interface HealthDto {
  version: string;
}

export interface ImdbResolvePayloadDto {
  imdbId: string;
  episodeNumber: number;
}

export interface ImdbResolveResponseDto {
  episodeImdbId: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const monitoringHealthCheck = (
  options?: SecondParameter<typeof catalogClientInstance<HealthDto>>,
) => {
  return catalogClientInstance<HealthDto>(
    { url: `/api/health`, method: 'GET' },
    options,
  );
};

export const monitoringHealthCheckWithToken = (
  token: string,
  options?: SecondParameter<typeof catalogClientInstance<HealthDto>>,
) => {
  return catalogClientInstance<HealthDto>(
    { url: `/api/health/${token}`, method: 'GET' },
    options,
  );
};

export const imdbResolverResolveSpecial = (
  token: string,
  imdbResolvePayloadDto: ImdbResolvePayloadDto,
  options?: SecondParameter<
    typeof catalogClientInstance<ImdbResolveResponseDto>
  >,
) => {
  return catalogClientInstance<ImdbResolveResponseDto>(
    {
      url: `/api/${token}/imdb/resolve/special`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: imdbResolvePayloadDto,
    },
    options,
  );
};

export type MonitoringHealthCheckResult = NonNullable<
  Awaited<ReturnType<typeof monitoringHealthCheck>>
>;
export type MonitoringHealthCheckWithTokenResult = NonNullable<
  Awaited<ReturnType<typeof monitoringHealthCheckWithToken>>
>;
export type ImdbResolverResolveSpecialResult = NonNullable<
  Awaited<ReturnType<typeof imdbResolverResolveSpecial>>
>;
