/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * StremHU Source
 * OpenAPI spec version: 0.1.0
 */
import { sourceClientInstance } from './source-client-instance.ts'

export interface AttributeExclusionCreateRequest {
  attributeId: string
}

export interface AttributeResponse {
  id: string
  name: string
  shortName?: string | null
  preferenceId?: string | null
}

export interface BehaviorHints {
  countryWhitelist?: string[] | null
  notWebReady?: boolean
  bingeGroup?: string | null
  filename?: string | null
}

export type ContentType = (typeof ContentType)[keyof typeof ContentType]

export const ContentType = {
  movie: 'movie',
  series: 'series',
  channel: 'channel',
  tv: 'tv',
} as const

export interface DDNSProviderResponse {
  id: string
  name: string
  websiteUrl: string
  domainRegex: string
}

export type ExtraName = (typeof ExtraName)[keyof typeof ExtraName]

export const ExtraName = {
  search: 'search',
  genre: 'genre',
  skip: 'skip',
} as const

export type ShortManifestResource =
  (typeof ShortManifestResource)[keyof typeof ShortManifestResource]

export const ShortManifestResource = {
  catalog: 'catalog',
  meta: 'meta',
  stream: 'stream',
  subtitles: 'subtitles',
  addon_catalog: 'addon_catalog',
} as const

export interface FullManifestResource {
  name: ShortManifestResource
  types: ContentType[]
  idPrefixes?: string[] | null
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
  input?: unknown
  ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface IndexerDefinitionResponse {
  id: string
  name: string
  url: string
  detailsPath: string
  requiresFullDownload: boolean
}

export interface IndexerLoginRequest {
  indexerId: string
  username: string
  password: string
}

export interface IndexerResponse {
  indexerId: string
  indexerDefinition: IndexerDefinitionResponse
  username: string
  downloadFullTorrent: boolean
  hitAndRun: boolean | null
  keepSeedSeconds: number | null
  updatedAt: string
  createdAt: string
}

export interface IndexerUpdateRequest {
  downloadFullTorrent?: boolean | null
  hitAndRun?: boolean | null
  keepSeedSeconds?: number | null
}

export interface KodiImdbStreamResponse {
  torrentName: string
  fileName: string
  seeders: number
  size: string
  indexer: IndexerDefinitionResponse
  mediaAttributes: AttributeResponse[]
  url: string
}

export interface KodiImdbStreamsResponse {
  streams: KodiImdbStreamResponse[]
  errors: string[]
}

export interface LoginRequest {
  username: string
  password: string
}

export interface ManifestExtra {
  name: ExtraName
  isRequired?: boolean | null
  options?: string[] | null
  optionsLimit?: number | null
}

export interface ManifestCatalog {
  type: ContentType
  id: string
  name: string
  extra?: ManifestExtra[] | null
}

export type ManifestConfigType =
  (typeof ManifestConfigType)[keyof typeof ManifestConfigType]

export const ManifestConfigType = {
  text: 'text',
  number: 'number',
  password: 'password',
  checkbox: 'checkbox',
  select: 'select',
} as const

export interface ManifestConfig {
  key: string
  type: ManifestConfigType
  default?: string | null
  title?: string | null
  options?: string[] | null
  required?: string | null
}

export interface ManifestBehaviorHints {
  adult?: boolean | null
  p2P?: boolean | null
  configurable?: boolean | null
  configurationRequired?: boolean | null
}

/**
 * Stremio addon manifest - https://stremio.github.io/stremio-addon-guide/
 */
export interface Manifest {
  id: string
  name: string
  description: string
  version: string
  resources: (ShortManifestResource | FullManifestResource)[]
  types: ContentType[]
  idPrefixes?: string[] | null
  catalogs: ManifestCatalog[]
  addonCatalogs?: ManifestCatalog[] | null
  config?: ManifestConfig[] | null
  background?: string | null
  logo?: string | null
  contactEmail?: string | null
  behaviorHints?: ManifestBehaviorHints | null
}

export interface MeUpdateRequest {
  username?: string | null
  password?: string | null
  torrentSeed?: number | null
  onlyBestTorrent?: boolean | null
}

export type MediaType = (typeof MediaType)[keyof typeof MediaType]

export const MediaType = {
  movie: 'movie',
  series: 'series',
} as const

export type PosterShape = (typeof PosterShape)[keyof typeof PosterShape]

export const PosterShape = {
  square: 'square',
  regular: 'regular',
  landscape: 'landscape',
} as const

export interface MetaLink {
  name: string
  category: string
  url: string
}

export interface MetaTrailer {
  ytId: string
  description: string
}

export interface MetaVideo {
  id: string
  title: string
  released?: string | null
  thumbnail?: string | null
  available?: boolean | null
  episode?: number | null
  season?: number | null
  trailer?: string | null
  overview?: string | null
}

export interface MetaDetailBehaviorHints {
  defaultVideoId?: string | null
  hasScheduledVideos?: boolean | null
}

export interface MetaDetail {
  id: string
  imdbId?: string | null
  type: ContentType
  name: string
  poster?: string | null
  posterShape?: PosterShape
  background?: string | null
  logo?: string | null
  description?: string | null
  imdbRating?: string | null
  releaseInfo?: string | null
  genres?: string[] | null
  cast?: string[] | null
  director?: string[] | null
  links?: MetaLink[] | null
  released?: string | null
  year?: string | null
  trailers?: MetaTrailer[] | null
  videos?: MetaVideo[] | null
  runtime?: string | null
  language?: string | null
  country?: string | null
  awards?: string | null
  website?: string | null
  behaviorHints?: MetaDetailBehaviorHints | null
  writer?: string[] | null
}

export interface MetaPreview {
  id: string
  imdbId?: string | null
  type: ContentType
  name: string
  poster?: string | null
  posterShape?: PosterShape
  background?: string | null
  logo?: string | null
  description?: string | null
  imdbRating?: string | null
  releaseInfo?: string | null
  genres?: string[] | null
  cast?: string[] | null
  director?: string[] | null
  links?: MetaLink[] | null
}

export type MetaResponseMeta = MetaDetail | { [key: string]: unknown }

export interface MetaResponse {
  meta: MetaResponseMeta
}

export type NetworkConnectionEnum =
  (typeof NetworkConnectionEnum)[keyof typeof NetworkConnectionEnum]

export const NetworkConnectionEnum = {
  local: 'local',
  public: 'public',
} as const

export interface NetworkAutoSettingsResponse {
  mode: 'auto'
  host: string
  token: string
  email: string
  connection: NetworkConnectionEnum
  provider: string
  ip: string
  expiresAt: string
  lastIpSyncAt: string
}

export interface NetworkAutoSetupRequest {
  mode: 'auto'
  host: string
  connection: NetworkConnectionEnum
  provider: string
  token: string
  email: string
}

export interface NetworkLocalSettingsResponse {
  mode: 'local'
  host: string
  ip: string
  expiresAt: string
}

export const NetworkLocalSetupRequestValue = {
  mode: 'local',
} as const
export type NetworkLocalSetupRequest = typeof NetworkLocalSetupRequestValue

export interface NetworkManualSettingsResponse {
  mode: 'manual'
  host: string
}

export interface NetworkManualSetupRequest {
  mode: 'manual'
  host: string
}

export interface NetworkSetupResponse {
  appUrl: string
  message: string
}

export interface RoleResponse {
  id: string
  name: string
}

export interface UserResponse {
  username: string
  torrentSeed?: number | null
  onlyBestTorrent?: boolean
  maxConcurrentStreams?: number | null
  id: string
  role: RoleResponse
  apiKey: string
  updatedAt: string
  createdAt: string
}

export interface PlaybackHistoryResponse {
  playbackId: string
  user: UserResponse
  indexerDefinition: IndexerDefinitionResponse
  torrentName: string | null
  fileName: string | null
  createdAt: string
}

export interface PagePlaybackHistoryResponse {
  items: PlaybackHistoryResponse[]
  total: number
  page: number
  size: number
  pages: number
}

export interface PairInitResponse {
  userCode: string
  deviceCode: string
  expiresAt: string
}

export interface PairStatusResponse {
  status: string
  token?: string | null
}

export interface PairVerifyRequest {
  userCode: string
}

export interface PlaybackResponse {
  playbackId: string
  user: UserResponse
  indexerDefinition: IndexerDefinitionResponse
  torrentName: string | null
  fileName: string | null
  createdAt: string
  progress: number
}

export interface PreferenceCreateRequest {
  preferenceId: string
  attributeIds: string[]
}

export interface PreferenceResponse {
  id: string
  name: string
  description: string
  emoji: string | null
  attributes: AttributeResponse[]
}

export interface PreferenceUpdateRequest {
  attributeIds: string[]
}

export interface PreferencesReorderRequest {
  preferenceIds: string[]
}

export interface RegisterRequest {
  username: string
  password: string
}

export interface RelaySettingsResponse {
  port: number
  downloadLimit: number
  uploadLimit: number
  connectionsLimit: number
  torrentConnectionsLimit: number
  enableUpnpAndNatpmp: boolean
}

export interface RelaySettingsUpdateRequest {
  port?: number | null
  downloadLimit?: number | null
  uploadLimit?: number | null
  connectionsLimit?: number | null
  torrentConnectionsLimit?: number | null
  enableUpnpAndNatpmp?: boolean | null
}

export interface StremioCatalogResponse {
  metas: MetaPreview[]
}

export interface StremioStream {
  name: string
  description: string
  url: string
  behaviorHints: BehaviorHints
}

export interface StremioStreams {
  streams: StremioStream[]
}

export interface SuccessResponse {
  success: boolean
  message?: string | null
}

export interface SystemSettingsResponse {
  hitAndRun: boolean
  keepSeedSeconds: number
  cacheRetentionSeconds: number
}

export interface SystemSettingsUpdateRequest {
  hitAndRun?: boolean | null
  keepSeedSeconds?: number | null
  cacheRetentionSeconds?: number | null
}

export interface SystemStatusResponse {
  configured: boolean
  version: string
  appUrl: string
  hostIp: string
  port: number
  isReverseProxy: boolean
}

export interface TorrentResponse {
  infoHash: string
  indexerDefinition: IndexerDefinitionResponse
  torrentId: string
  name: string
  downloadSpeed: number
  uploadSpeed: number
  downloaded: number
  uploaded: number
  total: number
  isPersisted: boolean
  fullDownload: boolean | null
  updatedAt: string
  createdAt: string
}

export interface TorrentUpdateRequest {
  isPersisted?: boolean | null
  fullDownload?: boolean | null
}

export interface UserCreateRequest {
  username: string
  torrentSeed?: number | null
  onlyBestTorrent?: boolean
  maxConcurrentStreams?: number | null
  password?: string | null
  roleId?: string
}

export interface UserUpdateRequest {
  username?: string | null
  password?: string | null
  roleId?: string | null
  torrentSeed?: number | null
  onlyBestTorrent?: boolean | null
  maxConcurrentStreams?: number | null
}

export type KodiFindStreamsParams = {
  season?: number | null
  episode?: number | null
}

export type PlaybacksGetHistoryListParams = {
  /**
   * @minimum 1
   */
  page?: number
  /**
   * @minimum 1
   * @maximum 100
   */
  size?: number
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Find List
 */
export const attributesFindList = (
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse[]>>,
) => {
  return sourceClientInstance<AttributeResponse[]>(
    { url: `/api/attributes/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get All
 */
export const preferencesGetAll = (
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    { url: `/api/preferences/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get
 */
export const preferencesGet = (
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    { url: `/api/preferences/${preferenceId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Health
 */
export const monitoringHealth = (
  options?: SecondParameter<typeof sourceClientInstance<SuccessResponse>>,
) => {
  return sourceClientInstance<SuccessResponse>(
    { url: `/api/health`, method: 'GET' },
    options,
  )
}

/**
 * @summary Register
 */
export const authRegister = (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequest,
    },
    options,
  )
}

/**
 * @summary Login
 */
export const authLogin = (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
    },
    options,
  )
}

/**
 * @summary Logout
 */
export const authLogout = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/auth/logout`, method: 'POST' },
    options,
  )
}

/**
 * Új eszközpárosítási folyamat kezdeményezése.
 * @summary Init
 */
export const pairingInit = (
  options?: SecondParameter<typeof sourceClientInstance<PairInitResponse>>,
) => {
  return sourceClientInstance<PairInitResponse>(
    { url: `/api/auth/pair/init`, method: 'POST' },
    options,
  )
}

/**
 * Eszköz párosítási státuszának lekérdezése.
 * @summary Status
 */
export const pairingStatus = (
  deviceCode: string,
  options?: SecondParameter<typeof sourceClientInstance<PairStatusResponse>>,
) => {
  return sourceClientInstance<PairStatusResponse>(
    { url: `/api/auth/pair/status/${deviceCode}`, method: 'GET' },
    options,
  )
}

/**
 * 4 jegyű párosító kód jóváhagyása a bejelentkezett felhasználó által.
 * @summary Verify
 */
export const pairingVerify = (
  pairVerifyRequest: PairVerifyRequest,
  options?: SecondParameter<typeof sourceClientInstance<SuccessResponse>>,
) => {
  return sourceClientInstance<SuccessResponse>(
    {
      url: `/api/auth/pair/verify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pairVerifyRequest,
    },
    options,
  )
}

/**
 * @summary Get List
 */
export const usersGetList = (
  options?: SecondParameter<typeof sourceClientInstance<UserResponse[]>>,
) => {
  return sourceClientInstance<UserResponse[]>(
    { url: `/api/users/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create
 */
export const usersCreate = (
  userCreateRequest: UserCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    {
      url: `/api/users/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userCreateRequest,
    },
    options,
  )
}

/**
 * @summary Get
 */
export const usersGet = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    { url: `/api/users/${userId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update
 */
export const usersUpdate = (
  userId: string,
  userUpdateRequest: UserUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    {
      url: `/api/users/${userId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: userUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Delete
 */
export const usersDelete = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/users/${userId}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Regenerate Api Key
 */
export const usersRegenerateApiKey = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    { url: `/api/users/${userId}/api_key/regenerate`, method: 'PUT' },
    options,
  )
}

/**
 * @summary Get Preferences
 */
export const usersGetPreferences = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    { url: `/api/users/${userId}/preferences/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Preference
 */
export const usersGetPreference = (
  userId: string,
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    { url: `/api/users/${userId}/preferences/${preferenceId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Preference Definitions
 */
export const usersGetPreferenceDefinitions = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    { url: `/api/users/${userId}/preferences/definitions/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create Preference Definition
 */
export const usersCreatePreferenceDefinition = (
  userId: string,
  preferenceCreateRequest: PreferenceCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    {
      url: `/api/users/${userId}/preferences/definitions/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: preferenceCreateRequest,
    },
    options,
  )
}

/**
 * @summary Reorder Preference Definitions
 */
export const usersReorderPreferenceDefinitions = (
  userId: string,
  preferencesReorderRequest: PreferencesReorderRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    {
      url: `/api/users/${userId}/preferences/definitions/reorder`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: preferencesReorderRequest,
    },
    options,
  )
}

/**
 * @summary Get Preference Definition
 */
export const usersGetPreferenceDefinition = (
  userId: string,
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    {
      url: `/api/users/${userId}/preferences/definitions/${preferenceId}`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Update Preference Definition
 */
export const usersUpdatePreferenceDefinition = (
  userId: string,
  preferenceId: string,
  preferenceUpdateRequest: PreferenceUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    {
      url: `/api/users/${userId}/preferences/definitions/${preferenceId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: preferenceUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Delete Preference Definition
 */
export const usersDeletePreferenceDefinition = (
  userId: string,
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    {
      url: `/api/users/${userId}/preferences/definitions/${preferenceId}`,
      method: 'DELETE',
    },
    options,
  )
}

/**
 * @summary Get Attributes
 */
export const usersGetAttributes = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse[]>>,
) => {
  return sourceClientInstance<AttributeResponse[]>(
    { url: `/api/users/${userId}/attributes/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Attribute Exclusions
 */
export const usersGetAttributeExclusions = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse[]>>,
) => {
  return sourceClientInstance<AttributeResponse[]>(
    { url: `/api/users/${userId}/attributes/exclusions/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create Attribute Exclusion
 */
export const usersCreateAttributeExclusion = (
  userId: string,
  attributeExclusionCreateRequest: AttributeExclusionCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse>>,
) => {
  return sourceClientInstance<AttributeResponse>(
    {
      url: `/api/users/${userId}/attributes/exclusions/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: attributeExclusionCreateRequest,
    },
    options,
  )
}

/**
 * @summary Delete Attribute Exclusion
 */
export const usersDeleteAttributeExclusion = (
  userId: string,
  attributeId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    {
      url: `/api/users/${userId}/attributes/exclusions/${attributeId}`,
      method: 'DELETE',
    },
    options,
  )
}

/**
 * @summary Get
 */
export const meGet = (
  options?: SecondParameter<typeof sourceClientInstance<UserResponse | null>>,
) => {
  return sourceClientInstance<UserResponse | null>(
    { url: `/api/me/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update
 */
export const meUpdate = (
  meUpdateRequest: MeUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    {
      url: `/api/me/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: meUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Regenerate Api Key
 */
export const meRegenerateApiKey = (
  options?: SecondParameter<typeof sourceClientInstance<UserResponse>>,
) => {
  return sourceClientInstance<UserResponse>(
    { url: `/api/me/api-key/regenerate`, method: 'PUT' },
    options,
  )
}

/**
 * @summary Get Preferences
 */
export const meGetPreferences = (
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    { url: `/api/me/preferences/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Preference
 */
export const meGetPreference = (
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    { url: `/api/me/preferences/${preferenceId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Preference Definitions
 */
export const meGetPreferenceDefinitions = (
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    { url: `/api/me/preferences/definitions/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create Preference Definition
 */
export const meCreatePreferenceDefinition = (
  preferenceCreateRequest: PreferenceCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    {
      url: `/api/me/preferences/definitions/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: preferenceCreateRequest,
    },
    options,
  )
}

/**
 * @summary Reorder Preference Definitions
 */
export const meReorderPreferenceDefinitions = (
  preferencesReorderRequest: PreferencesReorderRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse[]>>,
) => {
  return sourceClientInstance<PreferenceResponse[]>(
    {
      url: `/api/me/preferences/definitions/reorder`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: preferencesReorderRequest,
    },
    options,
  )
}

/**
 * @summary Get Preference Definition
 */
export const meGetPreferenceDefinition = (
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    { url: `/api/me/preferences/definitions/${preferenceId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update Preference Definition
 */
export const meUpdatePreferenceDefinition = (
  preferenceId: string,
  preferenceUpdateRequest: PreferenceUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<PreferenceResponse>>,
) => {
  return sourceClientInstance<PreferenceResponse>(
    {
      url: `/api/me/preferences/definitions/${preferenceId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: preferenceUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Delete Preference Definition
 */
export const meDeletePreferenceDefinition = (
  preferenceId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    {
      url: `/api/me/preferences/definitions/${preferenceId}`,
      method: 'DELETE',
    },
    options,
  )
}

/**
 * @summary Get Attributes
 */
export const meGetAttributes = (
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse[]>>,
) => {
  return sourceClientInstance<AttributeResponse[]>(
    { url: `/api/me/attributes/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Attribute Exclusions
 */
export const meGetAttributeExclusions = (
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse[]>>,
) => {
  return sourceClientInstance<AttributeResponse[]>(
    { url: `/api/me/attributes/exclusions/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create Attribute Exclusion
 */
export const meCreateAttributeExclusion = (
  attributeExclusionCreateRequest: AttributeExclusionCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<AttributeResponse>>,
) => {
  return sourceClientInstance<AttributeResponse>(
    {
      url: `/api/me/attributes/exclusions/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: attributeExclusionCreateRequest,
    },
    options,
  )
}

/**
 * @summary Delete Attribute Exclusion
 */
export const meDeleteAttributeExclusion = (
  attributeId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/me/attributes/exclusions/${attributeId}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Get Roles
 */
export const systemGetRoles = (
  options?: SecondParameter<typeof sourceClientInstance<RoleResponse[]>>,
) => {
  return sourceClientInstance<RoleResponse[]>(
    { url: `/api/system/roles`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Status
 */
export const systemGetStatus = (
  options?: SecondParameter<typeof sourceClientInstance<SystemStatusResponse>>,
) => {
  return sourceClientInstance<SystemStatusResponse>(
    { url: `/api/system/status`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Settings
 */
export const systemGetSettings = (
  options?: SecondParameter<
    typeof sourceClientInstance<SystemSettingsResponse>
  >,
) => {
  return sourceClientInstance<SystemSettingsResponse>(
    { url: `/api/system/settings`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update Settings
 */
export const systemUpdateSettings = (
  systemSettingsUpdateRequest: SystemSettingsUpdateRequest,
  options?: SecondParameter<
    typeof sourceClientInstance<SystemSettingsResponse>
  >,
) => {
  return sourceClientInstance<SystemSettingsResponse>(
    {
      url: `/api/system/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: systemSettingsUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Torrent Files Cleanup
 */
export const systemTorrentFilesCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/system/torrent-files/cleanup`, method: 'POST' },
    options,
  )
}

/**
 * @summary Indexers Cleanup
 */
export const systemIndexersCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/system/indexers/cleanup`, method: 'POST' },
    options,
  )
}

/**
 * @summary Restart
 */
export const systemRestart = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/system/restart`, method: 'POST' },
    options,
  )
}

/**
 * @summary Get Settings
 */
export const relayGetSettings = (
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsResponse>>,
) => {
  return sourceClientInstance<RelaySettingsResponse>(
    { url: `/api/relay/settings`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update Settings
 */
export const relayUpdateSettings = (
  relaySettingsUpdateRequest: RelaySettingsUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsResponse>>,
) => {
  return sourceClientInstance<RelaySettingsResponse>(
    {
      url: `/api/relay/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: relaySettingsUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Get Settings With Api Key
 */
export const relayGetSettingsWithApiKey = (
  apiKey: string,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsResponse>>,
) => {
  return sourceClientInstance<RelaySettingsResponse>(
    { url: `/api/${apiKey}/relay/settings`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update Settings With Api Key
 */
export const relayUpdateSettingsWithApiKey = (
  apiKey: string,
  relaySettingsUpdateRequest: RelaySettingsUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsResponse>>,
) => {
  return sourceClientInstance<RelaySettingsResponse>(
    {
      url: `/api/${apiKey}/relay/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: relaySettingsUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Get Settings
 */
export const networkGetSettings = (
  options?: SecondParameter<
    typeof sourceClientInstance<
      | NetworkLocalSettingsResponse
      | NetworkAutoSettingsResponse
      | NetworkManualSettingsResponse
    >
  >,
) => {
  return sourceClientInstance<
    | NetworkLocalSettingsResponse
    | NetworkAutoSettingsResponse
    | NetworkManualSettingsResponse
  >({ url: `/api/network/settings`, method: 'GET' }, options)
}

/**
 * @summary Get Ddns Providers
 */
export const networkGetDdnsProviders = (
  options?: SecondParameter<
    typeof sourceClientInstance<DDNSProviderResponse[]>
  >,
) => {
  return sourceClientInstance<DDNSProviderResponse[]>(
    { url: `/api/network/ddns/providers`, method: 'GET' },
    options,
  )
}

/**
 * @summary Setup
 */
export const networkSetup = (
  networkLocalSetupRequestNetworkAutoSetupRequestNetworkManualSetupRequest:
    | NetworkLocalSetupRequest
    | NetworkAutoSetupRequest
    | NetworkManualSetupRequest,
  options?: SecondParameter<typeof sourceClientInstance<NetworkSetupResponse>>,
) => {
  return sourceClientInstance<NetworkSetupResponse>(
    {
      url: `/api/network/setup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: networkLocalSetupRequestNetworkAutoSetupRequestNetworkManualSetupRequest,
    },
    options,
  )
}

/**
 * @summary Get List
 */
export const torrentsGetList = (
  options?: SecondParameter<typeof sourceClientInstance<TorrentResponse[]>>,
) => {
  return sourceClientInstance<TorrentResponse[]>(
    { url: `/api/torrents/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get One
 */
export const torrentsGetOne = (
  infoHash: string,
  options?: SecondParameter<typeof sourceClientInstance<TorrentResponse>>,
) => {
  return sourceClientInstance<TorrentResponse>(
    { url: `/api/torrents/${infoHash}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update
 */
export const torrentsUpdate = (
  infoHash: string,
  torrentUpdateRequest: TorrentUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<TorrentResponse>>,
) => {
  return sourceClientInstance<TorrentResponse>(
    {
      url: `/api/torrents/${infoHash}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: torrentUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Delete
 */
export const torrentsDelete = (
  infoHash: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/torrents/${infoHash}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Stream
 */
export const streamHeadStream = (
  apiKey: string,
  streamToken: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/${apiKey}/stream/${streamToken}`, method: 'HEAD' },
    options,
  )
}

/**
 * @summary Stream
 */
export const streamStream = (
  apiKey: string,
  streamToken: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/${apiKey}/stream/${streamToken}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Manifest
 */
export const stremioManifest = (
  apiKey: string,
  options?: SecondParameter<typeof sourceClientInstance<Manifest>>,
) => {
  return sourceClientInstance<Manifest>(
    { url: `/api/${apiKey}/stremio/manifest.json`, method: 'GET' },
    options,
  )
}

/**
 * @summary Configure
 */
export const stremioConfigure = (
  apiKey: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/${apiKey}/stremio/configure`, method: 'GET' },
    options,
  )
}

/**
 * @summary Streams
 */
export const stremioStreams = (
  apiKey: string,
  mediaType: MediaType,
  streamId: string,
  options?: SecondParameter<typeof sourceClientInstance<StremioStreams>>,
) => {
  return sourceClientInstance<StremioStreams>(
    {
      url: `/api/${apiKey}/stremio/stream/${mediaType}/${streamId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Catalog
 */
export const stremioCatalog = (
  apiKey: string,
  mediaType: MediaType,
  catalogId: string,
  options?: SecondParameter<
    typeof sourceClientInstance<StremioCatalogResponse>
  >,
) => {
  return sourceClientInstance<StremioCatalogResponse>(
    {
      url: `/api/${apiKey}/stremio/catalog/${mediaType}/${catalogId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Catalog With Extra
 */
export const stremioCatalogWithExtra = (
  apiKey: string,
  mediaType: MediaType,
  catalogId: string,
  extra: string,
  options?: SecondParameter<
    typeof sourceClientInstance<StremioCatalogResponse>
  >,
) => {
  return sourceClientInstance<StremioCatalogResponse>(
    {
      url: `/api/${apiKey}/stremio/catalog/${mediaType}/${catalogId}/${extra}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Meta
 */
export const stremioMeta = (
  apiKey: string,
  mediaType: MediaType,
  metaId: string,
  options?: SecondParameter<typeof sourceClientInstance<MetaResponse>>,
) => {
  return sourceClientInstance<MetaResponse>(
    {
      url: `/api/${apiKey}/stremio/meta/${mediaType}/${metaId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Find Streams
 */
export const kodiFindStreams = (
  apiKey: string,
  imdbId: string,
  params?: KodiFindStreamsParams,
  options?: SecondParameter<
    typeof sourceClientInstance<KodiImdbStreamsResponse>
  >,
) => {
  return sourceClientInstance<KodiImdbStreamsResponse>(
    {
      url: `/api/${apiKey}/kodi/imdb/${imdbId}/streams`,
      method: 'GET',
      params,
    },
    options,
  )
}

/**
 * Bejelentkezett indexerek listájának lekérése.
 * @summary Get List
 */
export const indexersGetList = (
  options?: SecondParameter<typeof sourceClientInstance<IndexerResponse[]>>,
) => {
  return sourceClientInstance<IndexerResponse[]>(
    { url: `/api/indexers/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get Definition List
 */
export const indexersGetDefinitionList = (
  options?: SecondParameter<
    typeof sourceClientInstance<IndexerDefinitionResponse[]>
  >,
) => {
  return sourceClientInstance<IndexerDefinitionResponse[]>(
    { url: `/api/indexers/definitions`, method: 'GET' },
    options,
  )
}

/**
 * @summary Login
 */
export const indexersLogin = (
  indexerLoginRequest: IndexerLoginRequest,
  options?: SecondParameter<typeof sourceClientInstance<IndexerResponse>>,
) => {
  return sourceClientInstance<IndexerResponse>(
    {
      url: `/api/indexers/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: indexerLoginRequest,
    },
    options,
  )
}

/**
 * Karbantartási takarítás manuális futtatása.
 * @summary Cleanup
 */
export const indexersCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/indexers/cleanup`, method: 'POST' },
    options,
  )
}

/**
 * @summary Update
 */
export const indexersUpdate = (
  indexerId: string,
  indexerUpdateRequest: IndexerUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<IndexerResponse>>,
) => {
  return sourceClientInstance<IndexerResponse>(
    {
      url: `/api/indexers/${indexerId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: indexerUpdateRequest,
    },
    options,
  )
}

/**
 * Indexer törlése/kijelentkeztetése.
 * @summary Delete
 */
export const indexersDelete = (
  indexerId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/indexers/${indexerId}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Get List
 */
export const playbacksGetList = (
  options?: SecondParameter<typeof sourceClientInstance<PlaybackResponse[]>>,
) => {
  return sourceClientInstance<PlaybackResponse[]>(
    { url: `/api/playbacks/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get History List
 */
export const playbacksGetHistoryList = (
  params?: PlaybacksGetHistoryListParams,
  options?: SecondParameter<
    typeof sourceClientInstance<PagePlaybackHistoryResponse>
  >,
) => {
  return sourceClientInstance<PagePlaybackHistoryResponse>(
    { url: `/api/playbacks/history`, method: 'GET', params },
    options,
  )
}

export type AttributesFindListResult = NonNullable<
  Awaited<ReturnType<typeof attributesFindList>>
>
export type PreferencesGetAllResult = NonNullable<
  Awaited<ReturnType<typeof preferencesGetAll>>
>
export type PreferencesGetResult = NonNullable<
  Awaited<ReturnType<typeof preferencesGet>>
>
export type MonitoringHealthResult = NonNullable<
  Awaited<ReturnType<typeof monitoringHealth>>
>
export type AuthRegisterResult = NonNullable<
  Awaited<ReturnType<typeof authRegister>>
>
export type AuthLoginResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
export type AuthLogoutResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>
export type PairingInitResult = NonNullable<
  Awaited<ReturnType<typeof pairingInit>>
>
export type PairingStatusResult = NonNullable<
  Awaited<ReturnType<typeof pairingStatus>>
>
export type PairingVerifyResult = NonNullable<
  Awaited<ReturnType<typeof pairingVerify>>
>
export type UsersGetListResult = NonNullable<
  Awaited<ReturnType<typeof usersGetList>>
>
export type UsersCreateResult = NonNullable<
  Awaited<ReturnType<typeof usersCreate>>
>
export type UsersGetResult = NonNullable<Awaited<ReturnType<typeof usersGet>>>
export type UsersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdate>>
>
export type UsersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof usersDelete>>
>
export type UsersRegenerateApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof usersRegenerateApiKey>>
>
export type UsersGetPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreferences>>
>
export type UsersGetPreferenceResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreference>>
>
export type UsersGetPreferenceDefinitionsResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreferenceDefinitions>>
>
export type UsersCreatePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof usersCreatePreferenceDefinition>>
>
export type UsersReorderPreferenceDefinitionsResult = NonNullable<
  Awaited<ReturnType<typeof usersReorderPreferenceDefinitions>>
>
export type UsersGetPreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreferenceDefinition>>
>
export type UsersUpdatePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdatePreferenceDefinition>>
>
export type UsersDeletePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof usersDeletePreferenceDefinition>>
>
export type UsersGetAttributesResult = NonNullable<
  Awaited<ReturnType<typeof usersGetAttributes>>
>
export type UsersGetAttributeExclusionsResult = NonNullable<
  Awaited<ReturnType<typeof usersGetAttributeExclusions>>
>
export type UsersCreateAttributeExclusionResult = NonNullable<
  Awaited<ReturnType<typeof usersCreateAttributeExclusion>>
>
export type UsersDeleteAttributeExclusionResult = NonNullable<
  Awaited<ReturnType<typeof usersDeleteAttributeExclusion>>
>
export type MeGetResult = NonNullable<Awaited<ReturnType<typeof meGet>>>
export type MeUpdateResult = NonNullable<Awaited<ReturnType<typeof meUpdate>>>
export type MeRegenerateApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof meRegenerateApiKey>>
>
export type MeGetPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreferences>>
>
export type MeGetPreferenceResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreference>>
>
export type MeGetPreferenceDefinitionsResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreferenceDefinitions>>
>
export type MeCreatePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof meCreatePreferenceDefinition>>
>
export type MeReorderPreferenceDefinitionsResult = NonNullable<
  Awaited<ReturnType<typeof meReorderPreferenceDefinitions>>
>
export type MeGetPreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreferenceDefinition>>
>
export type MeUpdatePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof meUpdatePreferenceDefinition>>
>
export type MeDeletePreferenceDefinitionResult = NonNullable<
  Awaited<ReturnType<typeof meDeletePreferenceDefinition>>
>
export type MeGetAttributesResult = NonNullable<
  Awaited<ReturnType<typeof meGetAttributes>>
>
export type MeGetAttributeExclusionsResult = NonNullable<
  Awaited<ReturnType<typeof meGetAttributeExclusions>>
>
export type MeCreateAttributeExclusionResult = NonNullable<
  Awaited<ReturnType<typeof meCreateAttributeExclusion>>
>
export type MeDeleteAttributeExclusionResult = NonNullable<
  Awaited<ReturnType<typeof meDeleteAttributeExclusion>>
>
export type SystemGetRolesResult = NonNullable<
  Awaited<ReturnType<typeof systemGetRoles>>
>
export type SystemGetStatusResult = NonNullable<
  Awaited<ReturnType<typeof systemGetStatus>>
>
export type SystemGetSettingsResult = NonNullable<
  Awaited<ReturnType<typeof systemGetSettings>>
>
export type SystemUpdateSettingsResult = NonNullable<
  Awaited<ReturnType<typeof systemUpdateSettings>>
>
export type SystemTorrentFilesCleanupResult = NonNullable<
  Awaited<ReturnType<typeof systemTorrentFilesCleanup>>
>
export type SystemIndexersCleanupResult = NonNullable<
  Awaited<ReturnType<typeof systemIndexersCleanup>>
>
export type SystemRestartResult = NonNullable<
  Awaited<ReturnType<typeof systemRestart>>
>
export type RelayGetSettingsResult = NonNullable<
  Awaited<ReturnType<typeof relayGetSettings>>
>
export type RelayUpdateSettingsResult = NonNullable<
  Awaited<ReturnType<typeof relayUpdateSettings>>
>
export type RelayGetSettingsWithApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof relayGetSettingsWithApiKey>>
>
export type RelayUpdateSettingsWithApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof relayUpdateSettingsWithApiKey>>
>
export type NetworkGetSettingsResult = NonNullable<
  Awaited<ReturnType<typeof networkGetSettings>>
>
export type NetworkGetDdnsProvidersResult = NonNullable<
  Awaited<ReturnType<typeof networkGetDdnsProviders>>
>
export type NetworkSetupResult = NonNullable<
  Awaited<ReturnType<typeof networkSetup>>
>
export type TorrentsGetListResult = NonNullable<
  Awaited<ReturnType<typeof torrentsGetList>>
>
export type TorrentsGetOneResult = NonNullable<
  Awaited<ReturnType<typeof torrentsGetOne>>
>
export type TorrentsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof torrentsUpdate>>
>
export type TorrentsDeleteResult = NonNullable<
  Awaited<ReturnType<typeof torrentsDelete>>
>
export type StreamHeadStreamResult = NonNullable<
  Awaited<ReturnType<typeof streamHeadStream>>
>
export type StreamStreamResult = NonNullable<
  Awaited<ReturnType<typeof streamStream>>
>
export type StremioManifestResult = NonNullable<
  Awaited<ReturnType<typeof stremioManifest>>
>
export type StremioConfigureResult = NonNullable<
  Awaited<ReturnType<typeof stremioConfigure>>
>
export type StremioStreamsResult = NonNullable<
  Awaited<ReturnType<typeof stremioStreams>>
>
export type StremioCatalogResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalog>>
>
export type StremioCatalogWithExtraResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalogWithExtra>>
>
export type StremioMetaResult = NonNullable<
  Awaited<ReturnType<typeof stremioMeta>>
>
export type KodiFindStreamsResult = NonNullable<
  Awaited<ReturnType<typeof kodiFindStreams>>
>
export type IndexersGetListResult = NonNullable<
  Awaited<ReturnType<typeof indexersGetList>>
>
export type IndexersGetDefinitionListResult = NonNullable<
  Awaited<ReturnType<typeof indexersGetDefinitionList>>
>
export type IndexersLoginResult = NonNullable<
  Awaited<ReturnType<typeof indexersLogin>>
>
export type IndexersCleanupResult = NonNullable<
  Awaited<ReturnType<typeof indexersCleanup>>
>
export type IndexersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof indexersUpdate>>
>
export type IndexersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof indexersDelete>>
>
export type PlaybacksGetListResult = NonNullable<
  Awaited<ReturnType<typeof playbacksGetList>>
>
export type PlaybacksGetHistoryListResult = NonNullable<
  Awaited<ReturnType<typeof playbacksGetHistoryList>>
>
