/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * StremHU Source - REST API
 * REST API dokumentáció
 * OpenAPI spec version: 1.0.0
 */
import { sourceClientInstance } from './source-client-instance'

export interface HealthDto {
  /** Az alkalmazás verziója */
  version: string
}

export interface SettingDto {
  /** Local IP engedélyezése */
  enebledlocalIp: boolean
  /**
   * Cím
   * @nullable
   */
  address: string | null
  /** Hit and Run védelem */
  hitAndRun: boolean
  /** Seedben tartás ideje (másodperc) */
  keepSeedSeconds: number
  /** Cache megőrzési ideje (másodperc) */
  cacheRetentionSeconds: number
  /**
   * Katalógus token
   * @nullable
   */
  catalogToken: string | null
}

export interface UpdateSettingDto {
  /** Local IP engedélyezése */
  enebledlocalIp?: boolean
  /** Cím */
  address?: string
  /** Hit and Run védelem */
  hitAndRun?: boolean
  /** Seedben tartás ideje (másodperc) */
  keepSeedSeconds?: number
  /** Cache megőrzési ideje (másodperc) */
  cacheRetentionSeconds?: number
  /**
   * Katalógus token
   * @nullable
   */
  catalogToken?: string | null
}

export interface LocalUrlRequestDto {
  /** IPv4 cím a helyi URL generálásához */
  ipv4: string
}

export interface LocalUrlDto {
  /** Helyi elérési út */
  localUrl: string
}

export interface AuthLoginDto {
  /** Felhasználónév */
  username: string
  /** Jelszó */
  password: string
}

/**
 * Felhasználói szerepkör
 */
export type UserRoleEnum = (typeof UserRoleEnum)[keyof typeof UserRoleEnum]

export const UserRoleEnum = {
  admin: 'admin',
  user: 'user',
} as const

export interface UserDto {
  /** Felhasználói szerepkör */
  userRole: UserRoleEnum
  /** Felhasználó egyedi azonosítója */
  id: string
  /** Felhasználónév */
  username: string
  /** API token */
  token: string
  /**
   * Torrent seed limit
   * @nullable
   */
  torrentSeed: number | null
  /** Csak a legjobb torrentek megjelenítése */
  onlyBestTorrent: boolean
  /** Utolsó frissítés időpontja */
  updatedAt: string
  /** Létrehozás időpontja */
  createdAt: string
}

export interface CatalogHealthDto {
  /** Katalógus verziója */
  version: string
}

export interface RelaySettingsDto {
  /** Port azonosító */
  port: number
  /** Letöltési korlát */
  downloadLimit: number
  /** Feltöltési korlát */
  uploadLimit: number
  /** Kapcsolatok korlátja */
  connectionsLimit: number
  /** Torrentenkénti kapcsolatok korlátja */
  torrentConnectionsLimit: number
  /** UPnP és NAT-PMP engedélyezése */
  enableUpnpAndNatpmp: boolean
}

export interface UpdateRelaySettingsDto {
  /**
   * Port azonosító
   * @minimum 1
   * @maximum 65535
   */
  port?: number
  /**
   * Letöltési korlát
   * @minimum 0
   */
  downloadLimit?: number
  /**
   * Feltöltési korlát
   * @minimum 0
   */
  uploadLimit?: number
  /**
   * Kapcsolatok korlátja
   * @minimum 0
   */
  connectionsLimit?: number
  /**
   * Torrentenkénti kapcsolatok korlátja
   * @minimum 0
   */
  torrentConnectionsLimit?: number
  /** UPnP és NAT-PMP engedélyezése */
  enableUpnpAndNatpmp?: boolean
}

/**
 * Tracker azonosító
 */
export type TrackerEnum = (typeof TrackerEnum)[keyof typeof TrackerEnum]

export const TrackerEnum = {
  ncore: 'ncore',
  bithumen: 'bithumen',
  majomparade: 'majomparade',
  insane: 'insane',
} as const

export interface LoginTrackerDto {
  /** Tracker azonosító */
  tracker: TrackerEnum
  /** Felhasználónév */
  username: string
  /** Jelszó */
  password: string
}

export interface TrackerDto {
  /** Tracker azonosító */
  tracker: TrackerEnum
  /** Felhasználónév */
  username: string
  /** Teljes torrent letöltése */
  downloadFullTorrent: boolean
  /**
   * Hit and Run védelem állapota
   * @nullable
   */
  hitAndRun: boolean | null
  /**
   * Seedben tartás ideje (másodperc)
   * @nullable
   */
  keepSeedSeconds: number | null
  /** Utolsó frissítés időpontja */
  updatedAt: string
  /** Létrehozás időpontja */
  createdAt: string
}

export interface UpdateTrackerDto {
  /**
   * Hit and Run védelem állapota
   * @nullable
   */
  hitAndRun?: boolean | null
  /**
   * Seedben tartás ideje (másodperc)
   * @nullable
   */
  keepSeedSeconds?: number | null
  /** Teljes torrent letöltése */
  downloadFullTorrent?: boolean
}

export interface TorrentDto {
  /** Tracker azonosító */
  tracker: TrackerEnum
  /** Torrent neve */
  name: string
  /** Letöltési sebesség */
  downloadSpeed: number
  /** Feltöltési sebesség */
  uploadSpeed: number
  /** Haladás (0-1) */
  progress: number
  /** Letöltött adat mennyisége */
  downloaded: number
  /** Feltöltött adat mennyisége */
  uploaded: number
  /** Teljes méret */
  total: number
  /** Info hash */
  infoHash: string
  /** Egyedi torrent azonosító */
  torrentId: string
  /** Mentve van-e az adatbázisba */
  isPersisted: boolean
  /**
   * Teljes letöltés állapota
   * @nullable
   */
  fullDownload: boolean | null
  /** Utolsó lejátszás időpontja */
  lastPlayedAt: string
  /** Utolsó frissítés időpontja */
  updatedAt: string
  /** Létrehozás időpontja */
  createdAt: string
}

export interface UpdateTorrentDto {
  /** Mentve van-e az adatbázisba */
  isPersisted?: boolean
  /**
   * Teljes letöltés állapota
   * @nullable
   */
  fullDownload?: boolean | null
}

export type PreferenceEnum =
  (typeof PreferenceEnum)[keyof typeof PreferenceEnum]

export const PreferenceEnum = {
  tracker: 'tracker',
  language: 'language',
  resolution: 'resolution',
  'video-quality': 'video-quality',
  source: 'source',
  'audio-quality': 'audio-quality',
  'audio-spatial': 'audio-spatial',
} as const

export interface TrackerPreferenceDto {
  preference: PreferenceEnum
  preferred: TrackerEnum[]
  blocked: TrackerEnum[]
}

export type LanguageEnum = (typeof LanguageEnum)[keyof typeof LanguageEnum]

export const LanguageEnum = {
  hu: 'hu',
  en: 'en',
} as const

export interface LanguagePreferenceDto {
  preference: PreferenceEnum
  preferred: LanguageEnum[]
  blocked: LanguageEnum[]
}

export type ResolutionEnum =
  (typeof ResolutionEnum)[keyof typeof ResolutionEnum]

export const ResolutionEnum = {
  '2160p': '2160p',
  '1080p': '1080p',
  '720p': '720p',
  '576p': '576p',
  '540p': '540p',
  '480p': '480p',
} as const

export interface ResolutionPreferenceDto {
  preference: PreferenceEnum
  preferred: ResolutionEnum[]
  blocked: ResolutionEnum[]
}

export type VideoQualityEnum =
  (typeof VideoQualityEnum)[keyof typeof VideoQualityEnum]

export const VideoQualityEnum = {
  'dolby-vision': 'dolby-vision',
  'hdr10+': 'hdr10+',
  hdr10: 'hdr10',
  hlg: 'hlg',
  sdr: 'sdr',
} as const

export interface VideoQualityPreferenceDto {
  preference: PreferenceEnum
  preferred: VideoQualityEnum[]
  blocked: VideoQualityEnum[]
}

export type SourceEnum = (typeof SourceEnum)[keyof typeof SourceEnum]

export const SourceEnum = {
  'disc-remux': 'disc-remux',
  'disc-rip': 'disc-rip',
  'web-dl': 'web-dl',
  'web-rip': 'web-rip',
  broadcast: 'broadcast',
  theatrical: 'theatrical',
  unknown: 'unknown',
} as const

export interface SourcePreferenceDto {
  preference: PreferenceEnum
  preferred: SourceEnum[]
  blocked: SourceEnum[]
}

export type AudioQualityEnum =
  (typeof AudioQualityEnum)[keyof typeof AudioQualityEnum]

export const AudioQualityEnum = {
  truehd: 'truehd',
  'dts-hd-ma': 'dts-hd-ma',
  ddp: 'ddp',
  dts: 'dts',
  dd: 'dd',
  aac: 'aac',
  unknown: 'unknown',
} as const

export interface AudioQualityPreferenceDto {
  preference: PreferenceEnum
  preferred: AudioQualityEnum[]
  blocked: AudioQualityEnum[]
}

export type AudioSpatialEnum =
  (typeof AudioSpatialEnum)[keyof typeof AudioSpatialEnum]

export const AudioSpatialEnum = {
  'dolby-atmos': 'dolby-atmos',
  'dts-x': 'dts-x',
} as const

export interface AudioSpatialPreferenceDto {
  preference: PreferenceEnum
  preferred: AudioSpatialEnum[]
  blocked: AudioSpatialEnum[]
}

export interface ReorderPreferencesDto {
  /** A preferenciák új sorrendje */
  preferences: PreferenceEnum[]
}

export interface CreateSetupDto {
  /** Felhasználónév */
  username: string
  /**
   * Jelszó
   * @minLength 1
   * @nullable
   */
  password: string | null
}

export interface StatusDto {
  hasAdminUser: boolean
  hasAddress: boolean
}

export interface CreateUserDto {
  /** Felhasználónév */
  username: string
  /**
   * Jelszó
   * @minLength 1
   * @nullable
   */
  password: string | null
}

export interface UpdateUserDto {
  /** Felhasználói szerepkör */
  userRole?: UserRoleEnum
  /** Felhasználónév */
  username?: string
  /** Jelszó */
  password?: string
  /**
   * Torrent seed limit
   * @nullable
   */
  torrentSeed?: number | null
  /** Csak a legjobb torrentek megjelenítése */
  onlyBestTorrent?: boolean
}

export interface MeDto {
  /**
   * Saját felhasználói adatok
   * @nullable
   */
  me: UserDto | null
}

export interface UpdateMeDto {
  /** Felhasználónév */
  username?: string
  /** Jelszó */
  password?: string
  /**
   * Torrent seed limit
   * @nullable
   */
  torrentSeed?: number | null
  /** Csak a legjobb torrentek megjelenítése */
  onlyBestTorrent?: boolean
}

export interface TrackerMetaDto {
  /** Tracker azonosító */
  value: TrackerEnum
  /** Megjelenített név */
  label: string
  /** Szükséges-e a teljes letöltés */
  requiresFullDownload: boolean
  /** Weboldal URL */
  url: string
  /** Részletek útvonala */
  detailsPath: string
}

export interface LanguageMetaDto {
  /** Nyelv értéke */
  value: LanguageEnum
  /** Megjelenített név */
  label: string
}

export interface ResolutionMetaDto {
  /** Felbontás értéke */
  value: ResolutionEnum
  /** Megjelenített név */
  label: string
}

export interface VideoQualityMetaDto {
  /** Videó minőség értéke */
  value: VideoQualityEnum
  /** Megjelenített név */
  label: string
}

export interface AudioQualityMetaDto {
  /** Audió minőség értéke */
  value: AudioQualityEnum
  /** Megjelenített név */
  label: string
}

export interface AudioSpatialMetaDto {
  /** Térhatású hang jellemző értéke */
  value: AudioSpatialEnum
  /** Megjelenített név */
  label: string
}

export interface SourceMetaDto {
  /** Forrás értéke */
  value: SourceEnum
  /** Megjelenített név */
  label: string
}

export interface KodiImdbStreamDto {
  /** Torrent fájl neve */
  torrentName: string
  /** Fájlnév a torrenten belül */
  fileName: string
  /** Seederek száma */
  seeders: number
  /** Emberi formátumú méret (pl. 2.5 GB) */
  size: string
  /** Tracker adatai */
  tracker: TrackerMetaDto
  /** Nyelvek listája */
  languages: LanguageMetaDto[]
  /** Felbontás adatai */
  resolution: ResolutionMetaDto
  /** Videó minőségi jellemzők */
  videoQualities: VideoQualityMetaDto[]
  /** Audió minőség */
  audioQuality?: AudioQualityMetaDto
  /** Térhatású hang jellemzők */
  audioSpatial?: AudioSpatialMetaDto
  /** Forrás adatai */
  source: SourceMetaDto
  /** Stream URL */
  url: string
}

export interface KodiImdbStreamsDto {
  /** Elérhető streamek listája */
  streams: KodiImdbStreamDto[]
  /** Hibák listája */
  errors: string[]
}

export interface TrackerPreferenceMetaDto {
  /** Tracker preferencia azonosító */
  value: PreferenceEnum
  /** Tracker elemek listája */
  items: TrackerMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface LanguagePreferenceMetaDto {
  /** Nyelv preferencia azonosító */
  value: PreferenceEnum
  /** Nyelv elemek listája */
  items: LanguageMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface ResolutionPreferenceMetaDto {
  /** Felbontás preferencia azonosító */
  value: PreferenceEnum
  /** Felbontás elemek listája */
  items: ResolutionMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface VideoQualityPreferenceMetaDto {
  /** Videó minőség preferencia azonosító */
  value: PreferenceEnum
  /** Videó minőség elemek listája */
  items: VideoQualityMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface SourcePreferenceMetaDto {
  /** Forrás preferencia azonosító */
  value: PreferenceEnum
  /** Forrás elemek listája */
  items: SourceMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface AudioQualityPreferenceMetaDto {
  /** Audió minőség preferencia azonosító */
  value: PreferenceEnum
  /** Audió minőség elemek listája */
  items: AudioQualityMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface AudioSpatialPreferenceMetaDto {
  /** Térhatású hang preferencia azonosító */
  value: PreferenceEnum
  /** Térhatású hang elemek listája */
  items: AudioSpatialMetaDto[]
  /** Megjelenített név */
  label: string
  /** Leírás */
  description: string
}

export interface UserRoleMetaDto {
  /** Felhasználói szerepkör értéke */
  value: UserRoleEnum
  /** Megjelenített név */
  label: string
}

export interface MetadataDto {
  /** Elérhető trackerek */
  trackers: TrackerMetaDto[]
  /** Elérhető felhasználói szerepkörök */
  userRoles: UserRoleMetaDto[]
  /** Elérhető preferenciák listája */
  preferences: (
    | TrackerPreferenceMetaDto
    | LanguagePreferenceMetaDto
    | ResolutionPreferenceMetaDto
    | VideoQualityPreferenceMetaDto
    | SourcePreferenceMetaDto
    | AudioQualityPreferenceMetaDto
    | AudioSpatialPreferenceMetaDto
  )[]
  /** Az alkalmazás verziója */
  version: string
  /** API végpont URL */
  endpoint: string
}

/**
 * Extra paraméter neve
 */
export type ManifestExtraDtoName =
  (typeof ManifestExtraDtoName)[keyof typeof ManifestExtraDtoName]

export const ManifestExtraDtoName = {
  search: 'search',
  genre: 'genre',
  skip: 'skip',
} as const

export interface ManifestExtraDto {
  /** Extra paraméter neve */
  name: ManifestExtraDtoName
  /** Kötelező-e a paraméter */
  isRequired?: boolean
  /** Választható opciók */
  options?: string[]
  /** Maximálisan választható opciók száma */
  optionsLimit?: number
}

/**
 * Tartalom típusa
 */
export type ManifestCatalogType =
  (typeof ManifestCatalogType)[keyof typeof ManifestCatalogType]

export const ManifestCatalogType = {
  movie: 'movie',
  series: 'series',
  channel: 'channel',
  tv: 'tv',
} as const

export interface ManifestCatalog {
  /** Tartalom típusa */
  type: ManifestCatalogType
  /** Katalógus azonosító */
  id: string
  /** Katalógus neve */
  name: string
  /** Extra szűrési paraméterek */
  extra?: ManifestExtraDto[]
}

/**
 * Konfiguráció típusa
 */
export type ManifestConfigDtoType =
  (typeof ManifestConfigDtoType)[keyof typeof ManifestConfigDtoType]

export const ManifestConfigDtoType = {
  text: 'text',
  number: 'number',
  password: 'password',
  checkbox: 'checkbox',
  select: 'select',
} as const

export interface ManifestConfigDto {
  /** Konfigurációs kulcs */
  key: string
  /** Konfiguráció típusa */
  type: ManifestConfigDtoType
  /** Alapértelmezett érték */
  default?: string
  /** Megjelenített cím */
  title?: string
  /** Választható opciók */
  options?: string[]
  /** Kötelező-e a megadása */
  required?: string
}

export interface ManifestBehaviorHintsDto {
  /** Felnőtt tartalom-e */
  adult?: boolean
  /** P2P alapú-e */
  p2p?: boolean
  /** Konfigurálható-e */
  configurable?: boolean
  /** Kötelező-e a konfiguráció */
  configurationRequired?: boolean
}

export type ManifestDtoResourcesItem = { [key: string]: unknown }

export type ManifestDtoTypesItem =
  (typeof ManifestDtoTypesItem)[keyof typeof ManifestDtoTypesItem]

export const ManifestDtoTypesItem = {
  movie: 'movie',
  series: 'series',
  channel: 'channel',
  tv: 'tv',
} as const

export interface ManifestDto {
  /** Addon egyedi azonosítója */
  id: string
  /** Addon neve */
  name: string
  /** Addon leírása */
  description: string
  /** Addon verziója */
  version: string
  /** Támogatott erőforrások listája */
  resources: ManifestDtoResourcesItem[]
  /** Támogatott tartalom típusok */
  types: ManifestDtoTypesItem[]
  /** ID előtagok */
  idPrefixes?: string[]
  /** Katalógusok listája */
  catalogs: ManifestCatalog[]
  /** Külső addon katalógusok */
  addonCatalogs?: ManifestCatalog[]
  /** Konfigurációs beállítások */
  config?: ManifestConfigDto[]
  /** Háttérkép URL */
  background?: string
  /** Logo URL */
  logo?: string
  /** Kapcsolati email */
  contactEmail?: string
  /** Viselkedési tippek */
  behaviorHints?: ManifestBehaviorHintsDto
}

export interface BehaviorHintsDto {
  countryWhitelist?: string[]
  notWebReady: boolean
  bingeGroup?: string
  filename?: string
}

export interface StremioStreamDto {
  name: string
  description: string
  url: string
  behaviorHints: BehaviorHintsDto
}

export interface StremioStreamsResponseDto {
  streams: StremioStreamDto[]
}

export type MediaTypeEnum = (typeof MediaTypeEnum)[keyof typeof MediaTypeEnum]

export const MediaTypeEnum = {
  movie: 'movie',
  series: 'series',
} as const

/**
 * Type of the content.
 */
export type ContentTypeEnum =
  (typeof ContentTypeEnum)[keyof typeof ContentTypeEnum]

export const ContentTypeEnum = {
  movie: 'movie',
  series: 'series',
  channel: 'channel',
  tv: 'tv',
} as const

/**
 * Poster can be square (1:1 aspect) or regular (1:0.675) or landscape (1:1.77).

Defaults to 'regular'.
 */
export type PosterShapeEnum =
  (typeof PosterShapeEnum)[keyof typeof PosterShapeEnum]

export const PosterShapeEnum = {
  square: 'square',
  regular: 'regular',
  landscape: 'landscape',
} as const

export interface MetaLinkDto {
  /** Megjelenített név pl. "Action", "Christopher Nolan" */
  name: string
  /** Kategória pl. "Genres" | "Cast" | "Writers" | "Directors" */
  category: string
  /** URL – lehet stremio:/// meta link is */
  url: string
}

export interface MetaPreviewDto {
  /** Type of the content. */
  type: ContentTypeEnum
  /** Poster can be square (1:1 aspect) or regular (1:0.675) or landscape (1:1.77).

  Defaults to 'regular'. */
  posterShape?: PosterShapeEnum
  /** Universal identifier.
  You may use a prefix unique to your addon.

  Example: 'yt_id:UCrDkAvwZum-UTjHmzDI2iIw' */
  id: string
  /** IMDb azonosító */
  imdb_id?: string
  /** Name of the content. */
  name: string
  /** URL to PNG of poster.

  Accepted aspect ratios: 1:0.675 (IMDb poster type) or 1:1 (square).

  You can use any resolution, as long as the file size is below 100kb.
  Below 50kb is recommended */
  poster?: string
  /** The background shown on the stremio detail page.

  Heavily encouraged if you want your content to look good.

  URL to PNG, max file size 500kb. */
  background?: string
  /** The logo shown on the stremio detail page.

  Encouraged if you want your content to look good.

  URL to PNG. */
  logo?: string
  /** A few sentences describing your content. */
  description?: string
  /** IMDb értékelés */
  imdbRating?: string
  /** Megjelenési információk */
  releaseInfo?: string
  /** Műfajok listája */
  genres?: string[]
  /** Szereplőgárda */
  cast?: string[]
  /** Rendező(k) */
  director?: string[]
  /** Can be used to link to internal pages of Stremio.

  example: array of actor / genre / director links. */
  links?: MetaLinkDto[]
}

export interface StremioCatalogDto {
  /** Meta adatok előnézeteinek listája */
  metas: MetaPreviewDto[]
  /** (másodpercben) Beállítja a Cache-Control fejléc max-age értékét ($cacheMaxAge).
  Felülírja a serveHTTP opciókban megadott globális cache időt. */
  cacheMaxAge?: number
  /** (másodpercben) Beállítja a Cache-Control fejléc stale-while-revalidate értékét ($staleRevalidate). */
  staleRevalidate?: number
  /** (másodpercben) Beállítja a Cache-Control fejléc stale-if-error értékét ($staleError). */
  staleError?: number
}

export interface MetaTrailerDto {
  /** YouTube azonosító */
  ytId: string
  /** Előzetes leírása */
  description: string
}

export interface MetaVideoDto {
  /** ID of the video. */
  id: string
  /** Title of the video. */
  title: string
  /** ISO 8601, publish date of the video.

  for episodes, this should be the initial air date.

  e.g. "2010-12-06T05:00:00.000Z" */
  released?: string
  /** URL to png of the video thumbnail, in the video's aspect ratio.

  max file size 5kb. */
  thumbnail?: string
  /** Set to true to explicitly state that this video is available for streaming, from your addon.

  No need to use this if you've passed stream. */
  available?: boolean
  /** Episode number, if applicable. */
  episode?: number
  /** Season number, if applicable. */
  season?: number
  /** YouTube ID of the trailer video; use if this is an episode for a series. */
  trailer?: string
  /** Video overview/summary */
  overview?: string
}

export interface MetaDetailBehaviorHintsDto {
  /** Alapértelmezett videó azonosító.
  Ha meg van adva, a részletező oldal közvetlenül ennek a videónak a streamjeit nyitja meg. */
  defaultVideoId?: string
  /** Vannak-e időzített videók */
  hasScheduledVideos?: boolean
}

export interface MetaDetailDto {
  /** Type of the content. */
  type: ContentTypeEnum
  /** Poster can be square (1:1 aspect) or regular (1:0.675) or landscape (1:1.77).

  Defaults to 'regular'. */
  posterShape?: PosterShapeEnum
  /** Universal identifier.
  You may use a prefix unique to your addon.

  Example: 'yt_id:UCrDkAvwZum-UTjHmzDI2iIw' */
  id: string
  /** IMDb azonosító */
  imdb_id?: string
  /** Name of the content. */
  name: string
  /** URL to PNG of poster.

  Accepted aspect ratios: 1:0.675 (IMDb poster type) or 1:1 (square).

  You can use any resolution, as long as the file size is below 100kb.
  Below 50kb is recommended */
  poster?: string
  /** The background shown on the stremio detail page.

  Heavily encouraged if you want your content to look good.

  URL to PNG, max file size 500kb. */
  background?: string
  /** The logo shown on the stremio detail page.

  Encouraged if you want your content to look good.

  URL to PNG. */
  logo?: string
  /** A few sentences describing your content. */
  description?: string
  /** IMDb értékelés */
  imdbRating?: string
  /** Megjelenési információk */
  releaseInfo?: string
  /** Műfajok listája */
  genres?: string[]
  /** Szereplőgárda */
  cast?: string[]
  /** Rendező(k) */
  director?: string[]
  /** Can be used to link to internal pages of Stremio.

  example: array of actor / genre / director links. */
  links?: MetaLinkDto[]
  /** ISO 8601, initial release date.

  For movies, this is the cinema debut.

  e.g. "2010-12-06T05:00:00.000Z" */
  released?: string
  /** Megjelenés éve */
  year?: string
  /** Előzetesek listája */
  trailers?: MetaTrailerDto[]
  /** Csatornákhoz és sorozatokhoz használatos.

  Ha nincs megadva (pl. filmnél), a Stremio feltételezi, hogy egy videó van, aminek az ID-ja megegyezik a meta ID-val. */
  videos?: MetaVideoDto[]
  /** Várható játékidő emberi formátumban.

  e.g. "120m" */
  runtime?: string
  /** Beszélt nyelv */
  language?: string
  /** Származási ország */
  country?: string
  /** Díjak leírása */
  awards?: string
  /** Hivatalos weboldal URL */
  website?: string
  /** Viselkedési tippek */
  behaviorHints?: MetaDetailBehaviorHintsDto
  /** Írók listája */
  writer?: string[]
}

export interface MetaDto {
  /** Meta adatok részletei */
  meta: MetaDetailDto
  /** (másodpercben) Beállítja a Cache-Control fejléc max-age értékét ($cacheMaxAge).
  Felülírja a serveHTTP opciókban megadott globális cache időt. */
  cacheMaxAge?: number
  /** (másodpercben) Beállítja a Cache-Control fejléc stale-while-revalidate értékét ($staleRevalidate). */
  staleRevalidate?: number
  /** (másodpercben) Beállítja a Cache-Control fejléc stale-if-error értékét ($staleError). */
  staleError?: number
}

export interface PairVerifyRequestDto {
  /** A megjelenő 4 jegyű kód */
  userCode: string
}

export interface PairVerifyDto {
  /** Sikeres volt-e a párosítás jóváhagyása */
  success: boolean
}

export interface PairInitDto {
  /** A 4 jegyű kód, amit a felhasználónak be kell gépelnie */
  userCode: string
  /** Az eszköz egyedi azonosítója a státusz lekérdezéséhez */
  deviceCode: string
  /** A kód lejárati ideje */
  expiresAt: string
}

export interface PairStatusRequestDto {
  deviceCode: string
}

/**
 * A párosítás állapota (pending, linked, expired)
 */
export type PairStatusDtoStatus =
  (typeof PairStatusDtoStatus)[keyof typeof PairStatusDtoStatus]

export const PairStatusDtoStatus = {
  pending: 'pending',
  linked: 'linked',
  expired: 'expired',
} as const

export interface PairStatusDto {
  /** A párosítás állapota (pending, linked, expired) */
  status: PairStatusDtoStatus
  /** A felhasználó API tokenje (csak 'linked' állapot esetén) */
  token?: string
}

export type UserPreferencesCreate201 = { [key: string]: unknown }

export type MePreferencesCreate201 = { [key: string]: unknown }

export type KodiIntegrationStreamsParams = {
  /**
   * Évad száma
   * @minimum 1
   */
  season?: number
  /**
   * Epizód száma
   * @minimum 1
   */
  episode?: number
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const monitoringHealth = (
  options?: SecondParameter<typeof sourceClientInstance<HealthDto>>,
) => {
  return sourceClientInstance<HealthDto>(
    { url: `/api/health`, method: 'GET' },
    options,
  )
}

export const settingsFindOne = (
  options?: SecondParameter<typeof sourceClientInstance<SettingDto>>,
) => {
  return sourceClientInstance<SettingDto>(
    { url: `/api/settings`, method: 'GET' },
    options,
  )
}

export const settingsUpdate = (
  updateSettingDto: UpdateSettingDto,
  options?: SecondParameter<typeof sourceClientInstance<SettingDto>>,
) => {
  return sourceClientInstance<SettingDto>(
    {
      url: `/api/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateSettingDto,
    },
    options,
  )
}

export const settingsBuildLocalUrl = (
  localUrlRequestDto: LocalUrlRequestDto,
  options?: SecondParameter<typeof sourceClientInstance<LocalUrlDto>>,
) => {
  return sourceClientInstance<LocalUrlDto>(
    {
      url: `/api/settings/local-url`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: localUrlRequestDto,
    },
    options,
  )
}

export const authLogin = (
  authLoginDto: AuthLoginDto,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: authLoginDto,
    },
    options,
  )
}

export const authLogout = (
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/auth/logout`, method: 'POST' },
    options,
  )
}

export const catalogHealth = (
  options?: SecondParameter<typeof sourceClientInstance<CatalogHealthDto>>,
) => {
  return sourceClientInstance<CatalogHealthDto>(
    { url: `/api/catalog/health`, method: 'GET' },
    options,
  )
}

export const relaySettingsInternalGet = (
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsDto>>,
) => {
  return sourceClientInstance<RelaySettingsDto>(
    { url: `/api/relay/settings`, method: 'GET' },
    options,
  )
}

export const relaySettingsInternalUpdate = (
  updateRelaySettingsDto: UpdateRelaySettingsDto,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsDto>>,
) => {
  return sourceClientInstance<RelaySettingsDto>(
    {
      url: `/api/relay/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateRelaySettingsDto,
    },
    options,
  )
}

export const relaySettingsIntegrationGet = (
  token: string,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsDto>>,
) => {
  return sourceClientInstance<RelaySettingsDto>(
    { url: `/api/${token}/relay/settings`, method: 'GET' },
    options,
  )
}

export const relaySettingsIntegrationUpdate = (
  token: string,
  updateRelaySettingsDto: UpdateRelaySettingsDto,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettingsDto>>,
) => {
  return sourceClientInstance<RelaySettingsDto>(
    {
      url: `/api/${token}/relay/settings`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateRelaySettingsDto,
    },
    options,
  )
}

export const trackersLogin = (
  loginTrackerDto: LoginTrackerDto,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    {
      url: `/api/trackers`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginTrackerDto,
    },
    options,
  )
}

export const trackersTrackers = (
  options?: SecondParameter<typeof sourceClientInstance<TrackerDto[]>>,
) => {
  return sourceClientInstance<TrackerDto[]>(
    { url: `/api/trackers`, method: 'GET' },
    options,
  )
}

export const trackersCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/trackers/cleanup`, method: 'POST' },
    options,
  )
}

export const trackersUpdate = (
  tracker: 'ncore' | 'bithumen' | 'majomparade' | 'insane',
  updateTrackerDto: UpdateTrackerDto,
  options?: SecondParameter<typeof sourceClientInstance<TrackerDto>>,
) => {
  return sourceClientInstance<TrackerDto>(
    {
      url: `/api/trackers/${tracker}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateTrackerDto,
    },
    options,
  )
}

export const trackersDelete = (
  tracker: 'ncore' | 'bithumen' | 'majomparade' | 'insane',
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/trackers/${tracker}`, method: 'DELETE' },
    options,
  )
}

export const torrentsCacheCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/torrents/cache/cleanup`, method: 'POST' },
    options,
  )
}

export const torrentsFind = (
  options?: SecondParameter<typeof sourceClientInstance<TorrentDto[]>>,
) => {
  return sourceClientInstance<TorrentDto[]>(
    { url: `/api/torrents`, method: 'GET' },
    options,
  )
}

export const torrentsUpdate = (
  infoHash: string,
  updateTorrentDto: UpdateTorrentDto,
  options?: SecondParameter<typeof sourceClientInstance<TorrentDto>>,
) => {
  return sourceClientInstance<TorrentDto>(
    {
      url: `/api/torrents/${infoHash}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateTorrentDto,
    },
    options,
  )
}

export const torrentsDelete = (
  infoHash: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/torrents/${infoHash}`, method: 'DELETE' },
    options,
  )
}

export const userPreferencesCreate = (
  userId: string,
  trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto:
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto,
  options?: SecondParameter<
    typeof sourceClientInstance<UserPreferencesCreate201>
  >,
) => {
  return sourceClientInstance<UserPreferencesCreate201>(
    {
      url: `/api/users/${userId}/preferences`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto,
    },
    options,
  )
}

export const userPreferencesFind = (
  userId: string,
  options?: SecondParameter<
    typeof sourceClientInstance<
      (
        | TrackerPreferenceDto
        | LanguagePreferenceDto
        | ResolutionPreferenceDto
        | VideoQualityPreferenceDto
        | SourcePreferenceDto
        | AudioQualityPreferenceDto
        | AudioSpatialPreferenceDto
      )[]
    >
  >,
) => {
  return sourceClientInstance<
    (
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    )[]
  >({ url: `/api/users/${userId}/preferences`, method: 'GET' }, options)
}

export const userPreferencesReorder = (
  userId: string,
  reorderPreferencesDto: ReorderPreferencesDto,
  options?: SecondParameter<
    typeof sourceClientInstance<
      (
        | TrackerPreferenceDto
        | LanguagePreferenceDto
        | ResolutionPreferenceDto
        | VideoQualityPreferenceDto
        | SourcePreferenceDto
        | AudioQualityPreferenceDto
        | AudioSpatialPreferenceDto
      )[]
    >
  >,
) => {
  return sourceClientInstance<
    (
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    )[]
  >(
    {
      url: `/api/users/${userId}/preferences/reorder`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: reorderPreferencesDto,
    },
    options,
  )
}

export const userPreferencesFindOne = (
  userId: string,
  preference: PreferenceEnum,
  options?: SecondParameter<
    typeof sourceClientInstance<
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    >
  >,
) => {
  return sourceClientInstance<
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto
  >(
    { url: `/api/users/${userId}/preferences/${preference}`, method: 'GET' },
    options,
  )
}

export const userPreferencesUpdate = (
  userId: string,
  preference: PreferenceEnum,
  trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto:
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto,
  options?: SecondParameter<
    typeof sourceClientInstance<
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    >
  >,
) => {
  return sourceClientInstance<
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto
  >(
    {
      url: `/api/users/${userId}/preferences/${preference}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto,
    },
    options,
  )
}

export const userPreferencesDelete = (
  userId: string,
  preference:
    | 'tracker'
    | 'language'
    | 'resolution'
    | 'video-quality'
    | 'source'
    | 'audio-quality'
    | 'audio-spatial',
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/users/${userId}/preferences/${preference}`, method: 'DELETE' },
    options,
  )
}

export const setupCreate = (
  createSetupDto: CreateSetupDto,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    {
      url: `/api/settings/setup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSetupDto,
    },
    options,
  )
}

export const setupStatus = (
  options?: SecondParameter<typeof sourceClientInstance<StatusDto>>,
) => {
  return sourceClientInstance<StatusDto>(
    { url: `/api/settings/setup/status`, method: 'GET' },
    options,
  )
}

export const usersCreate = (
  createUserDto: CreateUserDto,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    {
      url: `/api/users`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserDto,
    },
    options,
  )
}

export const usersFind = (
  options?: SecondParameter<typeof sourceClientInstance<UserDto[]>>,
) => {
  return sourceClientInstance<UserDto[]>(
    { url: `/api/users`, method: 'GET' },
    options,
  )
}

export const usersFindOne = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    { url: `/api/users/${userId}`, method: 'GET' },
    options,
  )
}

export const usersUpdateOne = (
  userId: string,
  updateUserDto: UpdateUserDto,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    {
      url: `/api/users/${userId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserDto,
    },
    options,
  )
}

export const usersDeleteOne = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/users/${userId}`, method: 'DELETE' },
    options,
  )
}

export const usersRegenerateToken = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    { url: `/api/users/${userId}/token/regenerate`, method: 'PUT' },
    options,
  )
}

export const meMe = (
  options?: SecondParameter<typeof sourceClientInstance<MeDto>>,
) => {
  return sourceClientInstance<MeDto>({ url: `/api/me`, method: 'GET' }, options)
}

export const meUpdateMe = (
  updateMeDto: UpdateMeDto,
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    {
      url: `/api/me`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateMeDto,
    },
    options,
  )
}

export const meRegenerateToken = (
  options?: SecondParameter<typeof sourceClientInstance<UserDto>>,
) => {
  return sourceClientInstance<UserDto>(
    { url: `/api/me/token/regenerate`, method: 'PUT' },
    options,
  )
}

export const mePreferencesCreate = (
  trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto:
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto,
  options?: SecondParameter<
    typeof sourceClientInstance<MePreferencesCreate201>
  >,
) => {
  return sourceClientInstance<MePreferencesCreate201>(
    {
      url: `/api/me/preference`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto,
    },
    options,
  )
}

export const mePreferencesFind = (
  options?: SecondParameter<
    typeof sourceClientInstance<
      (
        | TrackerPreferenceDto
        | LanguagePreferenceDto
        | ResolutionPreferenceDto
        | VideoQualityPreferenceDto
        | SourcePreferenceDto
        | AudioQualityPreferenceDto
        | AudioSpatialPreferenceDto
      )[]
    >
  >,
) => {
  return sourceClientInstance<
    (
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    )[]
  >({ url: `/api/me/preference`, method: 'GET' }, options)
}

export const mePreferencesReorder = (
  reorderPreferencesDto: ReorderPreferencesDto,
  options?: SecondParameter<
    typeof sourceClientInstance<
      (
        | TrackerPreferenceDto
        | LanguagePreferenceDto
        | ResolutionPreferenceDto
        | VideoQualityPreferenceDto
        | SourcePreferenceDto
        | AudioQualityPreferenceDto
        | AudioSpatialPreferenceDto
      )[]
    >
  >,
) => {
  return sourceClientInstance<
    (
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    )[]
  >(
    {
      url: `/api/me/preference/reorder`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: reorderPreferencesDto,
    },
    options,
  )
}

export const mePreferencesFindOne = (
  preference: PreferenceEnum,
  options?: SecondParameter<
    typeof sourceClientInstance<
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    >
  >,
) => {
  return sourceClientInstance<
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto
  >({ url: `/api/me/preference/${preference}`, method: 'GET' }, options)
}

export const mePreferencesUpdate = (
  preference: PreferenceEnum,
  trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto:
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto,
  options?: SecondParameter<
    typeof sourceClientInstance<
      | TrackerPreferenceDto
      | LanguagePreferenceDto
      | ResolutionPreferenceDto
      | VideoQualityPreferenceDto
      | SourcePreferenceDto
      | AudioQualityPreferenceDto
      | AudioSpatialPreferenceDto
    >
  >,
) => {
  return sourceClientInstance<
    | TrackerPreferenceDto
    | LanguagePreferenceDto
    | ResolutionPreferenceDto
    | VideoQualityPreferenceDto
    | SourcePreferenceDto
    | AudioQualityPreferenceDto
    | AudioSpatialPreferenceDto
  >(
    {
      url: `/api/me/preference/${preference}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: trackerPreferenceDtoLanguagePreferenceDtoResolutionPreferenceDtoVideoQualityPreferenceDtoSourcePreferenceDtoAudioQualityPreferenceDtoAudioSpatialPreferenceDto,
    },
    options,
  )
}

export const mePreferencesDelete = (
  preference:
    | 'tracker'
    | 'language'
    | 'resolution'
    | 'video-quality'
    | 'source'
    | 'audio-quality'
    | 'audio-spatial',
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/me/preference/${preference}`, method: 'DELETE' },
    options,
  )
}

export const kodiIntegrationStreams = (
  token: string,
  imdbId: string,
  params?: KodiIntegrationStreamsParams,
  options?: SecondParameter<typeof sourceClientInstance<KodiImdbStreamsDto>>,
) => {
  return sourceClientInstance<KodiImdbStreamsDto>(
    { url: `/api/${token}/kodi/imdb/${imdbId}/streams`, method: 'GET', params },
    options,
  )
}

export const metadataMetadata = (
  options?: SecondParameter<typeof sourceClientInstance<MetadataDto>>,
) => {
  return sourceClientInstance<MetadataDto>(
    { url: `/api/metadata`, method: 'GET' },
    options,
  )
}

export const stremioIntegrationConfigure = (
  token: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/${token}/stremio/configure`, method: 'GET' },
    options,
  )
}

export const stremioIntegrationManifest = (
  token: string,
  options?: SecondParameter<typeof sourceClientInstance<ManifestDto>>,
) => {
  return sourceClientInstance<ManifestDto>(
    { url: `/api/${token}/stremio/manifest.json`, method: 'GET' },
    options,
  )
}

export const stremioStreamsIntegrationStreams = (
  token: string,
  mediaType: 'movie' | 'series',
  id: string,
  options?: SecondParameter<
    typeof sourceClientInstance<StremioStreamsResponseDto>
  >,
) => {
  return sourceClientInstance<StremioStreamsResponseDto>(
    {
      url: `/api/${token}/stremio/stream/${mediaType}/${id}.json`,
      method: 'GET',
    },
    options,
  )
}

export const stremioCatalogsIntegrationCatalog = (
  token: string,
  mediaType: MediaTypeEnum,
  catalogId: string,
  options?: SecondParameter<typeof sourceClientInstance<StremioCatalogDto>>,
) => {
  return sourceClientInstance<StremioCatalogDto>(
    {
      url: `/api/${token}/stremio/catalog/${mediaType}/${catalogId}.json`,
      method: 'GET',
    },
    options,
  )
}

export const stremioCatalogsIntegrationCatalogWithExtra = (
  token: string,
  mediaType: MediaTypeEnum,
  catalogId: string,
  extra: string,
  options?: SecondParameter<typeof sourceClientInstance<StremioCatalogDto>>,
) => {
  return sourceClientInstance<StremioCatalogDto>(
    {
      url: `/api/${token}/stremio/catalog/${mediaType}/${catalogId}/${extra}.json`,
      method: 'GET',
    },
    options,
  )
}

export const stremioCatalogsIntegrationMeta = (
  token: string,
  mediaType: MediaTypeEnum,
  id: string,
  options?: SecondParameter<typeof sourceClientInstance<MetaDto>>,
) => {
  return sourceClientInstance<MetaDto>(
    {
      url: `/api/${token}/stremio/meta/${mediaType}/${id}.json`,
      method: 'GET',
    },
    options,
  )
}

export const playIntegrationPlay = (
  token: string,
  tracker: 'ncore' | 'bithumen' | 'majomparade' | 'insane',
  torrentId: string,
  fileIdx: number,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    {
      url: `/api/${token}/play/${tracker}/${torrentId}/${fileIdx}`,
      method: 'GET',
    },
    options,
  )
}

export const pairingsInternalVerify = (
  pairVerifyRequestDto: PairVerifyRequestDto,
  options?: SecondParameter<typeof sourceClientInstance<PairVerifyDto>>,
) => {
  return sourceClientInstance<PairVerifyDto>(
    {
      url: `/api/auth/pair/verify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pairVerifyRequestDto,
    },
    options,
  )
}

export const pairingsIntegrationInit = (
  options?: SecondParameter<typeof sourceClientInstance<PairInitDto>>,
) => {
  return sourceClientInstance<PairInitDto>(
    { url: `/api/auth/pair/init`, method: 'POST' },
    options,
  )
}

export const pairingsIntegrationStatus = (
  pairStatusRequestDto: PairStatusRequestDto,
  options?: SecondParameter<typeof sourceClientInstance<PairStatusDto>>,
) => {
  return sourceClientInstance<PairStatusDto>(
    {
      url: `/api/auth/pair/status`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pairStatusRequestDto,
    },
    options,
  )
}

export type MonitoringHealthResult = NonNullable<
  Awaited<ReturnType<typeof monitoringHealth>>
>
export type SettingsFindOneResult = NonNullable<
  Awaited<ReturnType<typeof settingsFindOne>>
>
export type SettingsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof settingsUpdate>>
>
export type SettingsBuildLocalUrlResult = NonNullable<
  Awaited<ReturnType<typeof settingsBuildLocalUrl>>
>
export type AuthLoginResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
export type AuthLogoutResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>
export type CatalogHealthResult = NonNullable<
  Awaited<ReturnType<typeof catalogHealth>>
>
export type RelaySettingsInternalGetResult = NonNullable<
  Awaited<ReturnType<typeof relaySettingsInternalGet>>
>
export type RelaySettingsInternalUpdateResult = NonNullable<
  Awaited<ReturnType<typeof relaySettingsInternalUpdate>>
>
export type RelaySettingsIntegrationGetResult = NonNullable<
  Awaited<ReturnType<typeof relaySettingsIntegrationGet>>
>
export type RelaySettingsIntegrationUpdateResult = NonNullable<
  Awaited<ReturnType<typeof relaySettingsIntegrationUpdate>>
>
export type TrackersLoginResult = NonNullable<
  Awaited<ReturnType<typeof trackersLogin>>
>
export type TrackersTrackersResult = NonNullable<
  Awaited<ReturnType<typeof trackersTrackers>>
>
export type TrackersCleanupResult = NonNullable<
  Awaited<ReturnType<typeof trackersCleanup>>
>
export type TrackersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof trackersUpdate>>
>
export type TrackersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof trackersDelete>>
>
export type TorrentsCacheCleanupResult = NonNullable<
  Awaited<ReturnType<typeof torrentsCacheCleanup>>
>
export type TorrentsFindResult = NonNullable<
  Awaited<ReturnType<typeof torrentsFind>>
>
export type TorrentsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof torrentsUpdate>>
>
export type TorrentsDeleteResult = NonNullable<
  Awaited<ReturnType<typeof torrentsDelete>>
>
export type UserPreferencesCreateResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesCreate>>
>
export type UserPreferencesFindResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesFind>>
>
export type UserPreferencesReorderResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesReorder>>
>
export type UserPreferencesFindOneResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesFindOne>>
>
export type UserPreferencesUpdateResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesUpdate>>
>
export type UserPreferencesDeleteResult = NonNullable<
  Awaited<ReturnType<typeof userPreferencesDelete>>
>
export type SetupCreateResult = NonNullable<
  Awaited<ReturnType<typeof setupCreate>>
>
export type SetupStatusResult = NonNullable<
  Awaited<ReturnType<typeof setupStatus>>
>
export type UsersCreateResult = NonNullable<
  Awaited<ReturnType<typeof usersCreate>>
>
export type UsersFindResult = NonNullable<Awaited<ReturnType<typeof usersFind>>>
export type UsersFindOneResult = NonNullable<
  Awaited<ReturnType<typeof usersFindOne>>
>
export type UsersUpdateOneResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdateOne>>
>
export type UsersDeleteOneResult = NonNullable<
  Awaited<ReturnType<typeof usersDeleteOne>>
>
export type UsersRegenerateTokenResult = NonNullable<
  Awaited<ReturnType<typeof usersRegenerateToken>>
>
export type MeMeResult = NonNullable<Awaited<ReturnType<typeof meMe>>>
export type MeUpdateMeResult = NonNullable<
  Awaited<ReturnType<typeof meUpdateMe>>
>
export type MeRegenerateTokenResult = NonNullable<
  Awaited<ReturnType<typeof meRegenerateToken>>
>
export type MePreferencesCreateResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesCreate>>
>
export type MePreferencesFindResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesFind>>
>
export type MePreferencesReorderResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesReorder>>
>
export type MePreferencesFindOneResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesFindOne>>
>
export type MePreferencesUpdateResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesUpdate>>
>
export type MePreferencesDeleteResult = NonNullable<
  Awaited<ReturnType<typeof mePreferencesDelete>>
>
export type KodiIntegrationStreamsResult = NonNullable<
  Awaited<ReturnType<typeof kodiIntegrationStreams>>
>
export type MetadataMetadataResult = NonNullable<
  Awaited<ReturnType<typeof metadataMetadata>>
>
export type StremioIntegrationConfigureResult = NonNullable<
  Awaited<ReturnType<typeof stremioIntegrationConfigure>>
>
export type StremioIntegrationManifestResult = NonNullable<
  Awaited<ReturnType<typeof stremioIntegrationManifest>>
>
export type StremioStreamsIntegrationStreamsResult = NonNullable<
  Awaited<ReturnType<typeof stremioStreamsIntegrationStreams>>
>
export type StremioCatalogsIntegrationCatalogResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalogsIntegrationCatalog>>
>
export type StremioCatalogsIntegrationCatalogWithExtraResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalogsIntegrationCatalogWithExtra>>
>
export type StremioCatalogsIntegrationMetaResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalogsIntegrationMeta>>
>
export type PlayIntegrationPlayResult = NonNullable<
  Awaited<ReturnType<typeof playIntegrationPlay>>
>
export type PairingsInternalVerifyResult = NonNullable<
  Awaited<ReturnType<typeof pairingsInternalVerify>>
>
export type PairingsIntegrationInitResult = NonNullable<
  Awaited<ReturnType<typeof pairingsIntegrationInit>>
>
export type PairingsIntegrationStatusResult = NonNullable<
  Awaited<ReturnType<typeof pairingsIntegrationStatus>>
>
