/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * StremHU Source
 * OpenAPI spec version: 0.1.0
 */
import { sourceClientInstance } from './source-client-instance'

export interface Attribute {
  id: string
  name: string
}

export interface BehaviorHints {
  countryWhitelist?: string[] | null
  notWebReady?: boolean
  bingeGroup?: string | null
  filename?: string | null
}

export type ContentType = (typeof ContentType)[keyof typeof ContentType]

export const ContentType = {
  movie: 'movie',
  series: 'series',
  channel: 'channel',
  tv: 'tv',
} as const

export type ExtraName = (typeof ExtraName)[keyof typeof ExtraName]

export const ExtraName = {
  search: 'search',
  genre: 'genre',
  skip: 'skip',
} as const

export type ShortManifestResource =
  (typeof ShortManifestResource)[keyof typeof ShortManifestResource]

export const ShortManifestResource = {
  catalog: 'catalog',
  meta: 'meta',
  stream: 'stream',
  subtitles: 'subtitles',
  addon_catalog: 'addon_catalog',
} as const

export interface FullManifestResource {
  name: ShortManifestResource
  types: ContentType[]
  idPrefixes?: string[] | null
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
  input?: unknown
  ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface Health {
  ok?: boolean
  startTime: number
}

export interface Indexer {
  id: string
  username: string
  downloadFullTorrent: boolean
  hitAndRun?: boolean | null
  keepSeedSeconds?: number | null
  updatedAt: string
  createdAt: string
}

export interface IndexerDefinition {
  id: string
  name: string
  url: string
  detailsPath: string
  requiresFullDownload: boolean
}

export type IndexerLoginCookies = { [key: string]: string } | null

export interface IndexerLogin {
  username: string
  password: string
  cookies?: IndexerLoginCookies
  indexer_id: string
}

export interface IndexerUpdate {
  hitAndRun?: boolean | null
  keepSeedSeconds?: number | null
  downloadFullTorrent?: boolean | null
}

export interface KodiImdbStream {
  torrentName: string
  fileName: string
  seeders: number
  size: string
  indexer: IndexerDefinition
  attributes?: Attribute[]
  url: string
}

export interface KodiImdbStreams {
  streams: KodiImdbStream[]
  errors: string[]
}

export interface LoginRequest {
  username: string
  password: string
}

export interface ManifestExtra {
  name: ExtraName
  isRequired?: boolean | null
  options?: string[] | null
  optionsLimit?: number | null
}

export interface ManifestCatalog {
  type: ContentType
  id: string
  name: string
  extra?: ManifestExtra[] | null
}

export type ManifestConfigType =
  (typeof ManifestConfigType)[keyof typeof ManifestConfigType]

export const ManifestConfigType = {
  text: 'text',
  number: 'number',
  password: 'password',
  checkbox: 'checkbox',
  select: 'select',
} as const

export interface ManifestConfig {
  key: string
  type: ManifestConfigType
  default?: string | null
  title?: string | null
  options?: string[] | null
  required?: string | null
}

export interface ManifestBehaviorHints {
  adult?: boolean | null
  p2P?: boolean | null
  configurable?: boolean | null
  configurationRequired?: boolean | null
}

/**
 * Stremio addon manifest - https://stremio.github.io/stremio-addon-guide/
 */
export interface Manifest {
  id: string
  name: string
  description: string
  version: string
  resources: (ShortManifestResource | FullManifestResource)[]
  types: ContentType[]
  idPrefixes?: string[] | null
  catalogs: ManifestCatalog[]
  addonCatalogs?: ManifestCatalog[] | null
  config?: ManifestConfig[] | null
  background?: string | null
  logo?: string | null
  contactEmail?: string | null
  behaviorHints?: ManifestBehaviorHints | null
}

export type PreferenceEnum =
  (typeof PreferenceEnum)[keyof typeof PreferenceEnum]

export const PreferenceEnum = {
  site: 'site',
  language: 'language',
  resolution: 'resolution',
  'video-quality': 'video-quality',
  source: 'source',
  'audio-quality': 'audio-quality',
  'audio-spatial': 'audio-spatial',
} as const

export interface MePreferenceCreateRequest {
  preference: PreferenceEnum
  preferred: string[]
}

export interface MePreferenceUpdateRequest {
  preferred: string[]
}

export interface MePreferencesReorderRequest {
  preferences: PreferenceEnum[]
}

export interface MeUpdateRequest {
  username?: string | null
  password?: string | null
  torrentSeed?: number | null
  onlyBestTorrent?: boolean | null
}

export type MediaType = (typeof MediaType)[keyof typeof MediaType]

export const MediaType = {
  movie: 'movie',
  series: 'series',
} as const

export type PosterShape = (typeof PosterShape)[keyof typeof PosterShape]

export const PosterShape = {
  square: 'square',
  regular: 'regular',
  landscape: 'landscape',
} as const

export interface MetaLink {
  name: string
  category: string
  url: string
}

export interface MetaTrailer {
  ytId: string
  description: string
}

export interface MetaVideo {
  id: string
  title: string
  released?: string | null
  thumbnail?: string | null
  available?: boolean | null
  episode?: number | null
  season?: number | null
  trailer?: string | null
  overview?: string | null
}

export interface MetaDetailBehaviorHints {
  defaultVideoId?: string | null
  hasScheduledVideos?: boolean | null
}

export interface MetaDetail {
  id: string
  imdbId?: string | null
  type: ContentType
  name: string
  poster?: string | null
  posterShape?: PosterShape | null
  background?: string | null
  logo?: string | null
  description?: string | null
  imdbRating?: string | null
  releaseInfo?: string | null
  genres?: string[] | null
  cast?: string[] | null
  director?: string[] | null
  links?: MetaLink[] | null
  released?: string | null
  year?: string | null
  trailers?: MetaTrailer[] | null
  videos?: MetaVideo[] | null
  runtime?: string | null
  language?: string | null
  country?: string | null
  awards?: string | null
  website?: string | null
  behaviorHints?: MetaDetailBehaviorHints | null
  writer?: string[] | null
}

export interface MetaPreview {
  id: string
  imdbId?: string | null
  type: ContentType
  name: string
  poster?: string | null
  posterShape?: PosterShape | null
  background?: string | null
  logo?: string | null
  description?: string | null
  imdbRating?: string | null
  releaseInfo?: string | null
  genres?: string[] | null
  cast?: string[] | null
  director?: string[] | null
  links?: MetaLink[] | null
}

export type MetaResponseMeta = MetaDetail | { [key: string]: unknown }

export interface MetaResponse {
  meta: MetaResponseMeta
}

export type NetworkConnectionEnum =
  (typeof NetworkConnectionEnum)[keyof typeof NetworkConnectionEnum]

export const NetworkConnectionEnum = {
  local: 'local',
  public: 'public',
} as const

export interface NetworkAutoSetup {
  mode: 'auto'
  host: string
  connection: NetworkConnectionEnum
  provider: string
  token: string
  email: string
}

export interface NetworkManualSetup {
  mode: 'manual'
  host: string
  reverseProxy: boolean
}

export interface PairInit {
  userCode: string
  deviceCode: string
  expiresAt: string
}

export interface PairStatus {
  status: string
  token?: string | null
}

export interface PairStatusRequest {
  deviceCode: string
}

export interface PairVerify {
  success: boolean
}

export interface PairVerifyRequest {
  userCode: string
}

export interface Preference {
  id: PreferenceEnum
  name: string
  description: string
  preferred: Attribute[]
}

export interface RegisterRequest {
  username: string
  password: string
}

export interface RelaySettings {
  port?: number
  downloadLimit?: number
  uploadLimit?: number
  connectionsLimit?: number
  torrentConnectionsLimit?: number
  enableUpnpAndNatpmp?: boolean
}

export interface RelaySettingsUpdateRequest {
  port?: number | null
  downloadLimit?: number | null
  uploadLimit?: number | null
  connectionsLimit?: number | null
  torrentConnectionsLimit?: number | null
  enableUpnpAndNatpmp?: boolean | null
}

export interface Role {
  id: string
  name: string
}

export interface StremioCatalogResponse {
  metas: MetaPreview[]
}

export interface StremioStream {
  name: string
  description: string
  url: string
  behaviorHints: BehaviorHints
}

export interface StremioStreams {
  streams: StremioStream[]
}

export interface SystemSettings {
  instanceId?: string
  hitAndRun?: boolean
  keepSeedSeconds?: number
  cacheRetentionSeconds?: number
  catalogToken?: string | null
}

export interface SystemSettingsSave {
  hitAndRun?: boolean | null
  keepSeedSeconds?: number | null
  cacheRetentionSeconds?: number | null
  catalogToken?: string | null
}

export interface Torrent {
  infoHash: string
  indexerDefinition: IndexerDefinition
  torrentId: string
  name: string
  downloadSpeed: number
  uploadSpeed: number
  downloaded: number
  uploaded: number
  total: number
  isPersisted: boolean
  fullDownload: boolean | null
  lastPlayedAt: string
  updatedAt: string
  createdAt: string
}

export interface TorrentUpdate {
  isPersisted?: boolean | null
  downloadFullTorrent?: boolean | null
}

export interface User {
  username: string
  torrentSeed?: number | null
  onlyBestTorrent?: boolean
  id: string
  role: Role
  token: string
  updatedAt: string
  createdAt: string
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole]

export const UserRole = {
  admin: 'admin',
  user: 'user',
} as const

export interface UserCreateRequest {
  username: string
  torrentSeed?: number | null
  onlyBestTorrent?: boolean
  password: string
  roleId?: UserRole
}

export interface UserPreferenceCreateRequest {
  preference: PreferenceEnum
  preferred: string[]
}

export interface UserPreferenceUpdateRequest {
  preferred: string[]
}

export interface UserPreferencesReorderRequest {
  preferences: PreferenceEnum[]
}

export interface UserUpdateRequest {
  username?: string | null
  password?: string | null
  roleId?: UserRole | null
  torrentSeed?: number | null
  onlyBestTorrent?: boolean | null
}

export type KodiGetStreamsParams = {
  season?: number | null
  episode?: number | null
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Health
 */
export const monitoringHealth = (
  options?: SecondParameter<typeof sourceClientInstance<Health>>,
) => {
  return sourceClientInstance<Health>(
    { url: `/api/health`, method: 'GET' },
    options,
  )
}

/**
 * @summary Register
 */
export const authRegister = (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequest,
    },
    options,
  )
}

/**
 * @summary Login
 */
export const authLogin = (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
    },
    options,
  )
}

/**
 * @summary Logout
 */
export const authLogout = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/auth/logout`, method: 'POST' },
    options,
  )
}

/**
 * Új eszközpárosítási folyamat kezdeményezése.
 * @summary Init
 */
export const pairingInit = (
  options?: SecondParameter<typeof sourceClientInstance<PairInit>>,
) => {
  return sourceClientInstance<PairInit>(
    { url: `/api/auth/pair/init`, method: 'POST' },
    options,
  )
}

/**
 * Eszköz párosítási státuszának lekérdezése.
 * @summary Status
 */
export const pairingStatus = (
  pairStatusRequest: PairStatusRequest,
  options?: SecondParameter<typeof sourceClientInstance<PairStatus>>,
) => {
  return sourceClientInstance<PairStatus>(
    {
      url: `/api/auth/pair/status`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pairStatusRequest,
    },
    options,
  )
}

/**
 * 4 jegyű párosító kód jóváhagyása a bejelentkezett felhasználó által.
 * @summary Verify
 */
export const pairingVerify = (
  pairVerifyRequest: PairVerifyRequest,
  options?: SecondParameter<typeof sourceClientInstance<PairVerify>>,
) => {
  return sourceClientInstance<PairVerify>(
    {
      url: `/api/auth/pair/verify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pairVerifyRequest,
    },
    options,
  )
}

/**
 * @summary Get List
 */
export const usersGetList = (
  options?: SecondParameter<typeof sourceClientInstance<User[]>>,
) => {
  return sourceClientInstance<User[]>(
    { url: `/api/users/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Create
 */
export const usersCreate = (
  userCreateRequest: UserCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    {
      url: `/api/users/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userCreateRequest,
    },
    options,
  )
}

/**
 * @summary Get
 */
export const usersGet = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    { url: `/api/users/${userId}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update
 */
export const usersUpdate = (
  userId: string,
  userUpdateRequest: UserUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    {
      url: `/api/users/${userId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: userUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Delete
 */
export const usersDelete = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/users/${userId}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Regenerate Api Key
 */
export const usersRegenerateApiKey = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    { url: `/api/users/${userId}/api_key/regenerate`, method: 'PUT' },
    options,
  )
}

/**
 * Lists all preferences for a specific user.
 * @summary Get Preferences
 */
export const usersGetPreferences = (
  userId: string,
  options?: SecondParameter<typeof sourceClientInstance<Preference[]>>,
) => {
  return sourceClientInstance<Preference[]>(
    { url: `/api/users/${userId}/preferences`, method: 'GET' },
    options,
  )
}

/**
 * Creates/adds a preference setting for a specific user.
 * @summary Create Preference
 */
export const usersCreatePreference = (
  userId: string,
  userPreferenceCreateRequest: UserPreferenceCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    {
      url: `/api/users/${userId}/preferences`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userPreferenceCreateRequest,
    },
    options,
  )
}

/**
 * Reorders the priority of preference categories for a specific user.
 * @summary Reorder Preferences
 */
export const usersReorderPreferences = (
  userId: string,
  userPreferencesReorderRequest: UserPreferencesReorderRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference[]>>,
) => {
  return sourceClientInstance<Preference[]>(
    {
      url: `/api/users/${userId}/preferences/reorder`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userPreferencesReorderRequest,
    },
    options,
  )
}

/**
 * Retrieves a specific preference setting for a specific user.
 * @summary Get Preference
 */
export const usersGetPreference = (
  userId: string,
  preference: PreferenceEnum,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    { url: `/api/users/${userId}/preferences/${preference}`, method: 'GET' },
    options,
  )
}

/**
 * Updates preferred attributes within an existing preference setting category for a specific user.
 * @summary Update Preference
 */
export const usersUpdatePreference = (
  userId: string,
  preference: PreferenceEnum,
  userPreferenceUpdateRequest: UserPreferenceUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    {
      url: `/api/users/${userId}/preferences/${preference}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: userPreferenceUpdateRequest,
    },
    options,
  )
}

/**
 * Deletes a specific preference category setting for a specific user.
 * @summary Delete Preference
 */
export const usersDeletePreference = (
  userId: string,
  preference: PreferenceEnum,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/users/${userId}/preferences/${preference}`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Get
 */
export const meGet = (
  options?: SecondParameter<typeof sourceClientInstance<User | null>>,
) => {
  return sourceClientInstance<User | null>(
    { url: `/api/me/`, method: 'GET' },
    options,
  )
}

/**
 * Updates the current user's profile information.
 * @summary Update
 */
export const meUpdate = (
  meUpdateRequest: MeUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    {
      url: `/api/me/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: meUpdateRequest,
    },
    options,
  )
}

/**
 * Regenerates the current user's API key.
 * @summary Regenerate Api Key
 */
export const meRegenerateApiKey = (
  options?: SecondParameter<typeof sourceClientInstance<User>>,
) => {
  return sourceClientInstance<User>(
    { url: `/api/me/api-key/regenerate`, method: 'PUT' },
    options,
  )
}

/**
 * Lists all of the current user's preference settings.
 * @summary Get Preferences
 */
export const meGetPreferences = (
  options?: SecondParameter<typeof sourceClientInstance<Preference[]>>,
) => {
  return sourceClientInstance<Preference[]>(
    { url: `/api/me/preferences`, method: 'GET' },
    options,
  )
}

/**
 * Adds/creates a preference setting with ordered preferred attributes.
 * @summary Create Preference
 */
export const meCreatePreference = (
  mePreferenceCreateRequest: MePreferenceCreateRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    {
      url: `/api/me/preferences`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: mePreferenceCreateRequest,
    },
    options,
  )
}

/**
 * Retrieves a specific preference setting for the current user.
 * @summary Get Preference
 */
export const meGetPreference = (
  preference: PreferenceEnum,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    { url: `/api/me/preferences/${preference}`, method: 'GET' },
    options,
  )
}

/**
 * Updates preferred attributes within an existing preference setting category.
 * @summary Update Preference
 */
export const meUpdatePreference = (
  preference: PreferenceEnum,
  mePreferenceUpdateRequest: MePreferenceUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference>>,
) => {
  return sourceClientInstance<Preference>(
    {
      url: `/api/me/preferences/${preference}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: mePreferenceUpdateRequest,
    },
    options,
  )
}

/**
 * Deletes a user's preference category setting.
 * @summary Delete Preference
 */
export const meDeletePreference = (
  preference: PreferenceEnum,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/me/preferences/${preference}`, method: 'DELETE' },
    options,
  )
}

/**
 * Reorders the priority of preference categories.
 * @summary Reorder Preferences
 */
export const meReorderPreferences = (
  mePreferencesReorderRequest: MePreferencesReorderRequest,
  options?: SecondParameter<typeof sourceClientInstance<Preference[]>>,
) => {
  return sourceClientInstance<Preference[]>(
    {
      url: `/api/me/preferences/reorder`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: mePreferencesReorderRequest,
    },
    options,
  )
}

/**
 * @summary Get App Settings
 */
export const settingGetAppSettings = (
  options?: SecondParameter<typeof sourceClientInstance<SystemSettings>>,
) => {
  return sourceClientInstance<SystemSettings>(
    { url: `/api/setting/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update App Settings
 */
export const settingUpdateAppSettings = (
  systemSettingsSave: SystemSettingsSave,
  options?: SecondParameter<typeof sourceClientInstance<SystemSettings>>,
) => {
  return sourceClientInstance<SystemSettings>(
    {
      url: `/api/setting/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: systemSettingsSave,
    },
    options,
  )
}

/**
 * @summary Get Relay Settings
 */
export const settingGetRelaySettings = (
  options?: SecondParameter<typeof sourceClientInstance<RelaySettings>>,
) => {
  return sourceClientInstance<RelaySettings>(
    { url: `/api/setting/relay/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update Relay Settings
 */
export const settingUpdateRelaySettings = (
  relaySettingsUpdateRequest: RelaySettingsUpdateRequest,
  options?: SecondParameter<typeof sourceClientInstance<RelaySettings>>,
) => {
  return sourceClientInstance<RelaySettings>(
    {
      url: `/api/setting/relay/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: relaySettingsUpdateRequest,
    },
    options,
  )
}

/**
 * @summary Config
 */
export const networkConfig = (
  networkAutoSetupNetworkManualSetup: NetworkAutoSetup | NetworkManualSetup,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    {
      url: `/api/network/config`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: networkAutoSetupNetworkManualSetup,
    },
    options,
  )
}

/**
 * @summary Reset
 */
export const networkReset = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/network/reset`, method: 'DELETE' },
    options,
  )
}

/**
 * @summary Get List
 */
export const torrentsGetList = (
  options?: SecondParameter<typeof sourceClientInstance<Torrent[]>>,
) => {
  return sourceClientInstance<Torrent[]>(
    { url: `/api/torrents/`, method: 'GET' },
    options,
  )
}

/**
 * @summary Get One
 */
export const torrentsGetOne = (
  infoHash: string,
  options?: SecondParameter<typeof sourceClientInstance<Torrent>>,
) => {
  return sourceClientInstance<Torrent>(
    { url: `/api/torrents/${infoHash}`, method: 'GET' },
    options,
  )
}

/**
 * @summary Update
 */
export const torrentsUpdate = (
  infoHash: string,
  torrentUpdate: TorrentUpdate,
  options?: SecondParameter<typeof sourceClientInstance<Torrent>>,
) => {
  return sourceClientInstance<Torrent>(
    {
      url: `/api/torrents/${infoHash}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: torrentUpdate,
    },
    options,
  )
}

/**
 * @summary Delete
 */
export const torrentsDelete = (
  infoHash: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/torrents/${infoHash}`, method: 'DELETE' },
    options,
  )
}

/**
 * Elindítja az elavult és inaktív torrent fájlok manuális törlését (Retention Cleanup).
 * @summary Cleanup
 */
export const torrentFilesCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/torrent-files/cleanup`, method: 'POST' },
    options,
  )
}

/**
 * @summary Stream
 */
export const streamHeadStream = (
  apiKey: string,
  indexerId: string,
  torrentId: string,
  fileIndex: number,
  sessionId: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    {
      url: `/api/${apiKey}/stream/${indexerId}/${torrentId}/${fileIndex}/${sessionId}`,
      method: 'HEAD',
    },
    options,
  )
}

/**
 * @summary Stream
 */
export const streamStream = (
  apiKey: string,
  indexerId: string,
  torrentId: string,
  fileIndex: number,
  sessionId: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    {
      url: `/api/${apiKey}/stream/${indexerId}/${torrentId}/${fileIndex}/${sessionId}`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Manifest
 */
export const stremioManifest = (
  apiKey: string,
  options?: SecondParameter<typeof sourceClientInstance<Manifest>>,
) => {
  return sourceClientInstance<Manifest>(
    { url: `/api/${apiKey}/stremio/manifest.json`, method: 'GET' },
    options,
  )
}

/**
 * @summary Configure
 */
export const stremioConfigure = (
  apiKey: string,
  options?: SecondParameter<typeof sourceClientInstance<unknown>>,
) => {
  return sourceClientInstance<unknown>(
    { url: `/api/${apiKey}/stremio/configure`, method: 'GET' },
    options,
  )
}

/**
 * @summary Streams
 */
export const stremioStreams = (
  apiKey: string,
  mediaType: MediaType,
  streamId: string,
  options?: SecondParameter<typeof sourceClientInstance<StremioStreams>>,
) => {
  return sourceClientInstance<StremioStreams>(
    {
      url: `/api/${apiKey}/stremio/stream/${mediaType}/${streamId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Catalog
 */
export const stremioCatalog = (
  apiKey: string,
  mediaType: MediaType,
  catalogId: string,
  options?: SecondParameter<
    typeof sourceClientInstance<StremioCatalogResponse>
  >,
) => {
  return sourceClientInstance<StremioCatalogResponse>(
    {
      url: `/api/${apiKey}/stremio/catalog/${mediaType}/${catalogId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Catalog With Extra
 */
export const stremioCatalogWithExtra = (
  apiKey: string,
  mediaType: MediaType,
  catalogId: string,
  extra: string,
  options?: SecondParameter<
    typeof sourceClientInstance<StremioCatalogResponse>
  >,
) => {
  return sourceClientInstance<StremioCatalogResponse>(
    {
      url: `/api/${apiKey}/stremio/catalog/${mediaType}/${catalogId}/${extra}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * @summary Meta
 */
export const stremioMeta = (
  apiKey: string,
  mediaType: MediaType,
  metaId: string,
  options?: SecondParameter<typeof sourceClientInstance<MetaResponse>>,
) => {
  return sourceClientInstance<MetaResponse>(
    {
      url: `/api/${apiKey}/stremio/meta/${mediaType}/${metaId}.json`,
      method: 'GET',
    },
    options,
  )
}

/**
 * Lekéri a Kodi-kompatibilis streameket IMDb ID (és opcionális évad/epizód) alapján.
 * @summary Get Streams
 */
export const kodiGetStreams = (
  apiKey: string,
  imdbId: string,
  params?: KodiGetStreamsParams,
  options?: SecondParameter<typeof sourceClientInstance<KodiImdbStreams>>,
) => {
  return sourceClientInstance<KodiImdbStreams>(
    {
      url: `/api/${apiKey}/kodi/imdb/${imdbId}/streams`,
      method: 'GET',
      params,
    },
    options,
  )
}

/**
 * Bejelentkezett indexerek listájának lekérése.
 * @summary Get List
 */
export const indexersGetList = (
  options?: SecondParameter<typeof sourceClientInstance<Indexer[]>>,
) => {
  return sourceClientInstance<Indexer[]>(
    { url: `/api/indexers/`, method: 'GET' },
    options,
  )
}

/**
 * Bejelentkezés egy új indexerre.
 * @summary Login
 */
export const indexersLogin = (
  indexerLogin: IndexerLogin,
  options?: SecondParameter<typeof sourceClientInstance<Indexer>>,
) => {
  return sourceClientInstance<Indexer>(
    {
      url: `/api/indexers/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: indexerLogin,
    },
    options,
  )
}

/**
 * Karbantartási takarítás manuális futtatása.
 * @summary Cleanup
 */
export const indexersCleanup = (
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/indexers/cleanup`, method: 'POST' },
    options,
  )
}

/**
 * Egy indexer beállításainak módosítása.
 * @summary Update
 */
export const indexersUpdate = (
  id: string,
  indexerUpdate: IndexerUpdate,
  options?: SecondParameter<typeof sourceClientInstance<Indexer>>,
) => {
  return sourceClientInstance<Indexer>(
    {
      url: `/api/indexers/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: indexerUpdate,
    },
    options,
  )
}

/**
 * Indexer törlése/kijelentkeztetése.
 * @summary Delete
 */
export const indexersDelete = (
  id: string,
  options?: SecondParameter<typeof sourceClientInstance<void>>,
) => {
  return sourceClientInstance<void>(
    { url: `/api/indexers/${id}`, method: 'DELETE' },
    options,
  )
}

export type MonitoringHealthResult = NonNullable<
  Awaited<ReturnType<typeof monitoringHealth>>
>
export type AuthRegisterResult = NonNullable<
  Awaited<ReturnType<typeof authRegister>>
>
export type AuthLoginResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
export type AuthLogoutResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>
export type PairingInitResult = NonNullable<
  Awaited<ReturnType<typeof pairingInit>>
>
export type PairingStatusResult = NonNullable<
  Awaited<ReturnType<typeof pairingStatus>>
>
export type PairingVerifyResult = NonNullable<
  Awaited<ReturnType<typeof pairingVerify>>
>
export type UsersGetListResult = NonNullable<
  Awaited<ReturnType<typeof usersGetList>>
>
export type UsersCreateResult = NonNullable<
  Awaited<ReturnType<typeof usersCreate>>
>
export type UsersGetResult = NonNullable<Awaited<ReturnType<typeof usersGet>>>
export type UsersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdate>>
>
export type UsersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof usersDelete>>
>
export type UsersRegenerateApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof usersRegenerateApiKey>>
>
export type UsersGetPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreferences>>
>
export type UsersCreatePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof usersCreatePreference>>
>
export type UsersReorderPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof usersReorderPreferences>>
>
export type UsersGetPreferenceResult = NonNullable<
  Awaited<ReturnType<typeof usersGetPreference>>
>
export type UsersUpdatePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdatePreference>>
>
export type UsersDeletePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof usersDeletePreference>>
>
export type MeGetResult = NonNullable<Awaited<ReturnType<typeof meGet>>>
export type MeUpdateResult = NonNullable<Awaited<ReturnType<typeof meUpdate>>>
export type MeRegenerateApiKeyResult = NonNullable<
  Awaited<ReturnType<typeof meRegenerateApiKey>>
>
export type MeGetPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreferences>>
>
export type MeCreatePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof meCreatePreference>>
>
export type MeGetPreferenceResult = NonNullable<
  Awaited<ReturnType<typeof meGetPreference>>
>
export type MeUpdatePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof meUpdatePreference>>
>
export type MeDeletePreferenceResult = NonNullable<
  Awaited<ReturnType<typeof meDeletePreference>>
>
export type MeReorderPreferencesResult = NonNullable<
  Awaited<ReturnType<typeof meReorderPreferences>>
>
export type SettingGetAppSettingsResult = NonNullable<
  Awaited<ReturnType<typeof settingGetAppSettings>>
>
export type SettingUpdateAppSettingsResult = NonNullable<
  Awaited<ReturnType<typeof settingUpdateAppSettings>>
>
export type SettingGetRelaySettingsResult = NonNullable<
  Awaited<ReturnType<typeof settingGetRelaySettings>>
>
export type SettingUpdateRelaySettingsResult = NonNullable<
  Awaited<ReturnType<typeof settingUpdateRelaySettings>>
>
export type NetworkConfigResult = NonNullable<
  Awaited<ReturnType<typeof networkConfig>>
>
export type NetworkResetResult = NonNullable<
  Awaited<ReturnType<typeof networkReset>>
>
export type TorrentsGetListResult = NonNullable<
  Awaited<ReturnType<typeof torrentsGetList>>
>
export type TorrentsGetOneResult = NonNullable<
  Awaited<ReturnType<typeof torrentsGetOne>>
>
export type TorrentsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof torrentsUpdate>>
>
export type TorrentsDeleteResult = NonNullable<
  Awaited<ReturnType<typeof torrentsDelete>>
>
export type TorrentFilesCleanupResult = NonNullable<
  Awaited<ReturnType<typeof torrentFilesCleanup>>
>
export type StreamHeadStreamResult = NonNullable<
  Awaited<ReturnType<typeof streamHeadStream>>
>
export type StreamStreamResult = NonNullable<
  Awaited<ReturnType<typeof streamStream>>
>
export type StremioManifestResult = NonNullable<
  Awaited<ReturnType<typeof stremioManifest>>
>
export type StremioConfigureResult = NonNullable<
  Awaited<ReturnType<typeof stremioConfigure>>
>
export type StremioStreamsResult = NonNullable<
  Awaited<ReturnType<typeof stremioStreams>>
>
export type StremioCatalogResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalog>>
>
export type StremioCatalogWithExtraResult = NonNullable<
  Awaited<ReturnType<typeof stremioCatalogWithExtra>>
>
export type StremioMetaResult = NonNullable<
  Awaited<ReturnType<typeof stremioMeta>>
>
export type KodiGetStreamsResult = NonNullable<
  Awaited<ReturnType<typeof kodiGetStreams>>
>
export type IndexersGetListResult = NonNullable<
  Awaited<ReturnType<typeof indexersGetList>>
>
export type IndexersLoginResult = NonNullable<
  Awaited<ReturnType<typeof indexersLogin>>
>
export type IndexersCleanupResult = NonNullable<
  Awaited<ReturnType<typeof indexersCleanup>>
>
export type IndexersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof indexersUpdate>>
>
export type IndexersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof indexersDelete>>
>
