name: PR Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"
      - "server/**"
      - "relay/**"
      - ".github/workflows/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Save PR Number
        run: echo ${{ github.event.pull_request.number }} > pr-number.txt

      - name: Upload PR Number
        uses: actions/upload-artifact@v7
        with:
          name: analysis-results
          path: pr-number.txt

  server:
    name: Server
    needs: setup
    uses: ./.github/workflows/reusable-test-and-build.yaml
    with:
      working-directory: ./server
    secrets: inherit

  client:
    name: Client
    needs: setup
    uses: ./.github/workflows/reusable-test-and-build.yaml
    with:
      working-directory: ./client
    secrets: inherit
