name: Test & Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Set Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "${{ inputs.working-directory }}/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check
        if: github.event_name == 'pull_request'
        run: npx eslint . --format stylish > eslint-report.txt || true
        continue-on-error: true

      - name: Type Check
        if: github.event_name == 'pull_request'
        run: npx tsc --noEmit > tsc-report.txt || true
        continue-on-error: true

      - name: Prettier Check
        if: github.event_name == 'pull_request'
        run: npx prettier --check . > prettier-report.txt || true
        continue-on-error: true

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v7
        if: github.event_name == 'pull_request'
        with:
          name: analysis-results
          path: |
            ${{ inputs.working-directory }}/eslint-report.txt
            ${{ inputs.working-directory }}/tsc-report.txt
            ${{ inputs.working-directory }}/prettier-report.txt

      - name: Test
        run: npm run test --if-present

      - name: Check for Test Results
        id: check_tests
        run: |
          if [ -f "junit.xml" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: always() && steps.check_tests.outputs.exists == 'true'
        with:
          name: test-results
          path: "${{ inputs.working-directory }}/junit.xml"

      - name: Build
        run: npm run build
