name: Test Report

on:
  workflow_run:
    workflows: [ "PR Check" ]
    types:
      - completed

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Get PR Number
        id: pr
        run: |
          if [ -f "analysis-results-server/server/pr-number.txt" ]; then
            echo "nr=$(cat analysis-results-server/server/pr-number.txt)" >> $GITHUB_OUTPUT
          elif [ -f "analysis-results-client/client/pr-number.txt" ]; then
            echo "nr=$(cat analysis-results-client/client/pr-number.txt)" >> $GITHUB_OUTPUT
          fi

      - name: Report Analysis (Server)
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_PULL_REQUEST: ${{ steps.pr.outputs.nr }}
        run: |
          if [ -d "analysis-results-server/server" ]; then
            cd server
            cat ../analysis-results-server/server/eslint-report.txt | reviewdog -f=eslint -reporter=github-pr-review -name="Server - eslint" -filter-mode=added -fail-on-error=false
            cat ../analysis-results-server/server/tsc-report.txt | reviewdog -f=tsc -reporter=github-pr-review -name="Server - tsc" -filter-mode=added -fail-on-error=false
            cat ../analysis-results-server/server/prettier-report.txt | reviewdog -f=prettier -reporter=github-pr-review -name="Server - prettier" -filter-mode=added -fail-on-error=false
            cd ..
          fi

      - name: Report Analysis (Client)
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_PULL_REQUEST: ${{ steps.pr.outputs.nr }}
        run: |
          if [ -d "analysis-results-client/client" ]; then
            cd client
            cat ../analysis-results-client/client/eslint-report.txt | reviewdog -f=eslint -reporter=github-pr-review -name="Client - eslint" -filter-mode=added -fail-on-error=false
            cat ../analysis-results-client/client/tsc-report.txt | reviewdog -f=tsc -reporter=github-pr-review -name="Client - tsc" -filter-mode=added -fail-on-error=false
            cat ../analysis-results-client/client/prettier-report.txt | reviewdog -f=prettier -reporter=github-pr-review -name="Client - prettier" -filter-mode=added -fail-on-error=false
            cd ..
          fi

      - name: Check Artifacts Existence
        id: check_artifacts
        run: |
          if [ -d "test-results-server" ]; then echo "server_exists=true" >> $GITHUB_OUTPUT; fi
          if [ -d "test-results-client" ]; then echo "client_exists=true" >> $GITHUB_OUTPUT; fi

      - name: Server Test Report
        if: steps.check_artifacts.outputs.server_exists == 'true'
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results-server
          name: "Server - tests"
          path: "**/junit.xml"
          reporter: jest-junit

      - name: Client Test Report
        if: steps.check_artifacts.outputs.client_exists == 'true'
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results-client
          name: "Client - tests"
          path: "**/junit.xml"
          reporter: jest-junit
